### ISSUE TITLE
Request: Auras for (fixed) template locations, not actors

### ISSUE THREAD

**Issue by dmaneyapanda** [kandashi/Active-Auras#100]
I am trying to implement an aura for the 5e Silence spell.  Silence is a ranged 20 foot sphere, with effects: "Any creature or object entirely inside the sphere is immune to thunder damage, and creatures are deafened while entirely inside it. Casting a spell that includes a verbal component is impossible there."  So the silence aura is not based on a specific actor having the DAE, but a location/template.  Not sure if doing this is even possible.

I did try creating it as a non-transfer effect on the silence spell, but as expected essentially all it does is put the aura onto any targeted actors at cast time.  Then those actors have the 20-foot aura fixed to them, and as they move around the aura moves with them, which is definitely not how the spell is intended to work.  (If no actors are targeted, then the caster gains concentration, but no targets are affected and no one gets the aura, even if they later move into the template area.)  

If multiple nearby creatures are targeted, all sorts of weird things happen.  Moving other creatures into range will cause double sets of the aura affect to appear.  And (similar to #85) those applied aura affects won't come off until you separate everyone outside the aura radius of everyone else with the effect, including all the initial targeted/aura sources.  Plus some of the initial targets get multiple copies of some of the effects, but not all, and not the same ones on different actors.

I guess a workaround would be to create a fake actor, drop them where you want the effect to be, and then target them with the spell, but that's obviously not the ideal workflow for this.

**Comment by kandashi** [comment]
This is a enhancement Ive been thinking about for a quite, good to have an issue here to track now

**Comment by kandashi** [comment]
closed with #112
