### ISSUE TITLE
Token Magic Conflict w/ DAE? 

### ISSUE THREAD

**Issue by 8woot8** [kandashi/Active-Auras#104]
![Token Magic Issue w_DAE](https://user-images.githubusercontent.com/80236010/110272460-226bdb00-7f7f-11eb-9b6f-f728aba76ac9.PNG)

Hi, 

I attempted to use Token Magic w/ DAE and I found that the aura effects get replicated multiple times within DAE.  I'm not sure why this is and whether this is an issue w/ the Token Magic or DAE modules.  Appreciate your assistance troubleshooting this. 

Thanks.

**Comment by 8woot8** [comment]
I wonder if the issue is that TMFX hasn't been updated for the last 4 months?  It lists that the last compatible Foundry version was 0.6.6....... aside from writing up a macro, any other way to achieve the filtering affects that TMFX can do automatically?

**Comment by kandashi** [comment]
can you confirm which version you are on, and the setup of the aura details

**Comment by 8woot8** [comment]
Using ver 0.1.56 for Active Auras.  For TMFX, ver 0.4.4.  For Foundry 0.7.9.  

Had the same issue as siliconsaint in that filter effects would not remove.  They would add, but not remove when chars moved out of range of the auras.  The filters would also get wonky when you move chars in and out of two active auras.  I had two active auras on two different characters, Aura of Vitality (bard spell), and Aura of Protection (paladin passive aura) that overlapped each other.  Required manual removal of the filter effects.

**Comment by kandashi** [comment]
I should have a fix for this and #105 soon

**Comment by kandashi** [comment]
fixed in the 0.1.57 release
