### ISSUE TITLE
Toggling an Aura tmfx while within range will add but not remove

### ISSUE THREAD

**Issue by siliconsaint** [kandashi/Active-Auras#105]
(Follow up to discord chat, I know it's easier to track issues here).

I've setup a paladin to always apply Aura buff/debuffs, but to selectively allow glowing effects to toggle.  I've noticed that toggling the glow effect on will make nearby (10') enemies/allies glow, but toggling it back off will not stop the glowing effect. This leads to the following issues:
1. Moving away while glow toggled off, leaves tokens glowing indefinitely
2. Turning the glow back on, THEN backing away removes the glow

![aura-issue](https://user-images.githubusercontent.com/56798973/110323516-b28f3c00-7fe2-11eb-86de-7de4cd97b4ce.gif)

**Comment by kandashi** [comment]
Can you confimg:
-you are on the latest build? 
- the actuall active effect is still present on the tokens when the aura source moves away
-

**Comment by siliconsaint** [comment]
- Active-Auras 0.1.56
- My Aura config has two DAE entries, the stat part is always on (passive) while the glow is toggled. Moving away from token removes the passive stat effect, but the glow remains on targets.

I think this is directly related with toggling an aura component while inside the 'effect zone'.  

I'm attaching my Aura of Protection config in case there is something suspect with it. (I use a custom glow effect, but you can use TMFX glow)

[fvtt-Item-Aura_of_Protection.json.zip](https://github.com/kandashi/Active-Auras/files/6105125/fvtt-Item-Aura_of_Protection.json.zip)

**Comment by kandashi** [comment]
This seems to be caused by multiple auras coming from the same item being disabled at different times. Possible to fix but performance hit limits for now

**Comment by siliconsaint** [comment]
Per discussion with Kandashi, I've updated my config to separate the two DAE entries into individual Aura's. It is working as expected now.
