### ISSUE TITLE
Auras Transferring Seems to have Stopped functioning after last update

### ISSUE THREAD

**Issue by KellethDregar** [kandashi/Active-Auras#110]
Having trouble getting Auras to work after the last update, this error shows up in the logs when moving a token into the aura range of another. 
This is an error occurring between two PC tokens.
![activeauras](https://user-images.githubusercontent.com/79947702/111840631-1ebb4b00-88d3-11eb-8bf9-e4360a5b3a53.png)

This one is from NPC to NPC auras or NPC to PC
![activeauras2](https://user-images.githubusercontent.com/79947702/111844191-eae32400-88d8-11eb-9865-00b0e4db1869.png)

**Comment by kandashi** [comment]
A substancial rework is coming soon, If this persists after that I'll take a closer look

**Comment by kandashi** [comment]
I found this issue while testing, it should be fixed in the next update
