### ISSUE TITLE
Aura of Protection + DAE SRD Bless = 21d4 bonus

### ISSUE THREAD

**Issue by siliconsaint** [kandashi/Active-Auras#111]
On two separate occasions, with the Paladin class, using Aura of Protection (Active Auras) and having DAE SRD Bless, the buff has resolved to 21d4 on saves.  Something must be concatenating incorrectly?

I'm not saying it's your module(s), but something is up!

<img width="230" alt="Screen Shot 2021-03-20 at 2 49 09 PM" src="https://user-images.githubusercontent.com/56798973/111882343-7917e280-898b-11eb-8548-89061fea4910.png">

**Comment by kandashi** [comment]
its a DAE SRD issue, ill fix for next release. Simple fix is to change `1d4` to `+1d4`
