### ISSUE TITLE
PC to PC Aura not Applying

### ISSUE THREAD

**Issue by KellethDregar** [kandashi/Active-Auras#113]
Just checked aura application following the fix for #110. Confirmed that auras from NPC to NPC and NPC to PC are transferring properly.

When testing PC to PC aura transfer I see the below error persisting:
![activeaurasPCtoPC](https://user-images.githubusercontent.com/79947702/112059530-54aa3a80-8b32-11eb-905b-d45fd84031c2.png)

**Comment by kandashi** [comment]
can you export me the item and give a list of your active modules

**Comment by Smoldar-og** [comment]
Having the same issue. Active-Auras, DAE and libWrapper active only. These are the items I'm using
[Auras.zip](https://github.com/kandashi/Active-Auras/files/6185421/Auras.zip)

**Comment by KellethDregar** [comment]
Same as Smoldar above me, although I'm testing with the items in the "Active Auras Auras" compendium you've included with the module. Namely the Auras of protection.

**Comment by kandashi** [comment]
right, ill look into it now. Those were the auras I was testing with too...

**Comment by Smoldar-og** [comment]
Doing some testing and fooling around;
Found this:

The auras that add condition immunities added alone on the actor does work as intended.

Auras that changes rolls using any @ on the effect value, works on the actor that have the aura but bugs out auras for other actors in general.

Activated Aura of Courage and Devotion only (Immunity to Frighten and Charm) and the effects imported correctly to the other actors, even showing up on the sheet.

Activated the Aura of Protection last and it started showing on the other actors, but whenever the other actors try to roll any dice that the aura affect, results on a error.

dice.js:168 Error: The dice roll formula 1d20 + 1 + undefined did not produce a numeric outcome.
    at Roll.evaluate (foundry.js:7677)
    at Roll.roll (foundry.js:7704)
    at _roll (dice.js:166)
    at Object.callback (dice.js:232)
    at Dialog.submit (foundry.js:13149)
    at Dialog._onClickButton (foundry.js:13112)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)
    
    Changing the original aura to a flat value "solved" the issue.
    
    Hope that it helps =D

**Comment by kandashi** [comment]
that does help thanks
