### ISSUE TITLE
Token magic fx glow is not sticking to aura range. 

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [kandashi/Active-Auras#115]
what seems to happen is if you use a token and bring it close to a char with the auras and then take it away sometimes it will still keep the glowing effect from the tokenmagic fx macro even tho you are outside of the auras range. the effect of the active effects isnt present but the token glow is still happening.

**Comment by kandashi** [comment]
if the aura effect is not present then its likely a rapid update causing the issue
