### ISSUE TITLE
Token height isnt taken into consideration on activation/ deactivation. 

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [kandashi/Active-Auras#116]
one of my pcs is flying next to the pc who has the aura. yet they are 25 ft up and the aura is 10 ft. but they are still receiving the benefits.

**Comment by kandashi** [comment]
Is `check token height` ticked in the aura details?

**Comment by ThingsCouldGetDicey** [comment]
i didnt see that sorry.

**Comment by kandashi** [comment]
no problem 👍
