### ISSUE TITLE
Active Auras on templetes are activating only 1 effect.

### ISSUE THREAD

**Issue by uLotUu** [kandashi/Active-Auras#117]
I was trying to make "Darkness" spell using Active Auras. The problem is - when I use a macro to put the spell effect on a template only first effet is activated. So in my case I'm adding "Blilnd" and "Invisibility". Only "Blind" works. However If I remove blind, "Invisibility" works fine. 

The second issue is an effect with macro trigger. Can't make it trigger no matter what. As soon as I'm adding a macro to an effect, that effect is no longer being applied to a template.

**Comment by kandashi** [comment]
ahh yes, i see the error in the bundled macro, ill fix this soon
