### ISSUE TITLE
Creature Type not working

### ISSUE THREAD

**Issue by Smoldar-og** [kandashi/Active-Auras#119]
The creature type check is not working, no errors are shown and no effects appear on other actors. Only Aura and DAE + Dependencies activated as modules

The selected actor is the aura bearer, with the Elf type check. Both actors are on range and have Elf as Type/Race but no aura appear.

Also, if possible, could the check be made with possibility of using wild cards, for example %Genasi as the value on the aura would search for any actors with Genasi at the end regardless if using "Fire Genasi, Wind Genasi" or even homebrewed races/types

![Type pic](https://user-images.githubusercontent.com/69021004/112088804-34e53780-8b6f-11eb-972d-b47278e823da.jpg)

**Comment by kandashi** [comment]
Creature type is simply meant to check the standard 5e types, not individual races. 
Aberration, Beast, Celestial, Construct, Dragon, Elemental, Fey, Fiend, Giant, Humanoid, Monstrosity, Ooze, Plant, Undead. 

If a compelling case is made, i might add in a secondary option to add this in
