### ISSUE TITLE
Cannot add macro.execute to Auras on Template

### ISSUE THREAD

**Issue by uLotUu** [kandashi/Active-Auras#122]
Not sure if it's a bug or a limitation, but currently it's impossible to add "macro.execute" to an effect and then transfer it to a template.

**Comment by kandashi** [comment]
can you explain a bit more what you mean by "impossible", what errors happen, what dosnt work etc

**Comment by uLotUu** [comment]
When I create an effect and use macro to add it on a template it works fine. However when I try to add a macro.execute to that effect (even simple chat macro), that effect is not triggering on the template anymore (nothing happens).

**Comment by kandashi** [comment]
Ive found the issue, fix going out in 0.2.04
