### ISSUE TITLE
[Info] Aura and radius don't appear to be needed for Template effects

### ISSUE THREAD

**Issue by dmaneyapanda** [kandashi/Active-Auras#124]
I haven't tested extensively, but I don't think you actually need to even set up an effect as an aura, or set the radius.  (Because I forgot to, and it still seemed to work.)

You just need to:
* Copy the Attach to Template macro into an item's ItemMacro
* Set the OnUse to ItemMacro
* Create an effect that does something

And it seems to work to create a template aura that applies the effect.

Not sure that this is important info, but thought I would share it.

**Comment by kandashi** [comment]
Hum, quite correct. I will adjust the readme file
