### ISSUE TITLE
CUB conditions stuck when using CUB.macro in an aura

### ISSUE THREAD

**Issue by dmaneyapanda** [kandashi/Active-Auras#125]
When:
* Using template aura effects
* Having ATL installed and enabled
* Creating an aura effect that applies a CUB effect (using dae.macro.CUB)

The aura gets applied the first time normally, but a "phantom" CUB effect remains on the client when it departs the aura (but apparently not on the server).  This phantom effect prevents the aura from working properly going forward.

Disabling ATL causes the issue to disappear.

Possibly this is related to Condition Automation as well (since I first discovered the issue when applying the Blinded CUB status, which CA also uses to change token vision).

**Comment by kandashi** [comment]
I cant seem to replicate this locally, which is frustrating

**Comment by dmaneyapanda** [comment]
I think you asked in discord about exporting my world.  I am happy to do that if you tell me how to do it.  Do you just mean copy/zip everything in the data/worlds/<worldname> folder?  Or is there an export function somewhere?

**Comment by dmaneyapanda** [comment]
Just brainstorming here, but possibly there's an additional requirement, that the CUB effect not only invokes Condition Automation, but also applies it's own DAE statuses?  (in my case, grants ADV and attacks have DISADV)

I can't see why that would change anything, but just noting it as a possibility since you can't reproduce.

**Comment by kandashi** [comment]
what I'll do is push the next release with a few fixes, then we'll see if this continues

**Comment by dmaneyapanda** [comment]
FYI, as of today with all mods updated today, I am still having this issue.  Disabling ATL still fixes it.  It does not seem to affect all tokens, just some of them.  (In my case, a paladin who had other DAE active on him, perhaps that is notable.)  Other NPC tokens with no other AE seemed to work correctly.

**Comment by dmaneyapanda** [comment]
Possibly related?: https://gitlab.com/tposney/dae/-/issues/152

**Comment by kandashi** [comment]
Quite possibly yes

**Comment by vanderleitelesjr** [comment]
Same is happening to me, even if I only have the required modules enabled (DAE, AA and CUB)

![Sticky CUB Effect](https://user-images.githubusercontent.com/40318093/121740630-bea00380-cad3-11eb-9076-9918e8f4a26f.gif)

Something else I noticed is that the aura is being applied to the origin token even if Ignore Self is checked, but I am not sure if that is simply due to some issues with how it set it up.
