### ISSUE TITLE
Removing the Template from a template aura leaves aura effects on tokens

### ISSUE THREAD

**Issue by dmaneyapanda** [kandashi/Active-Auras#126]
If you have a template aura, and there are tokens inside the aura which have the aura effects on them, and then the template is deleted (say, if it is a concentration spell and concentration is ended, but really any way of deleting the template works, even just manually deleting it), then the DAE effects on the affected tokens are not removed automatically as is desirable, and must instead be removed manually.

**Comment by kandashi** [comment]
Found the error, fix going out in 0.2.04, will need a rework of macros
