### ISSUE TITLE
Tokens effected by an active aura that are moving simultaneously causes stuttering.

### ISSUE THREAD

**Issue by SpectreWraith** [kandashi/Active-Auras#127]
I've noticed that when selecting multiple tokens simultaneously and moving them rapidly with the arrow keys applies many active auras of the same time, effectively duplicating them on the several sheets, who's tokens you have selected.

**Comment by kandashi** [comment]
Ive seen more reports of stuttering over the last few days, I might place an "in combat" check to prevent this sort of situation
