### ISSUE TITLE
Macro Repeat function doesn't work.

### ISSUE THREAD

**Issue by uLotUu** [kandashi/Active-Auras#129]
Auras no longer trigger based on "Macro Repeat" in DAE tab if you apply it to template.
Sometimes "Special Expiry for the applied effect" doesn't trigger also - but I can't find the pattern on that. (I think you need to add "blank" special durration for it to trigger).

**Comment by kandashi** [comment]
Can you provide json exports of that items that cause issues

**Comment by uLotUu** [comment]
[fvtt-Item-Hunger_of_Hadar.zip](https://github.com/kandashi/Active-Auras/files/6214792/fvtt-Item-Hunger_of_Hadar.zip)

I've used your CloudKill macro here. It should trigger at the end of turn, but triggers only once. I've also ticked "Expire at the end of turn", cause it doesn't work here either.

**Comment by kandashi** [comment]
Hum, i can confirm. Im not sure why this is happening, ill talk to Tposney

**Comment by kandashi** [comment]
The macro repeat function of DAE/TimesUp does call the macro, however this specific macro was not configured to use that funciton.
A repeat macro will be called with `args[0] === "each"` which the macro must read, or simply ignore the args[0] entirely
