### ISSUE TITLE
AA Effect Is Not Removed When Token Is Removed From Combat

### ISSUE THREAD

**Issue by OmnesPotens** [kandashi/Active-Auras#130]
**Foundry Version:** 0.7.9

**System:** dnd5e 1.2.4

**Potentially Relevant Installed Modules:** 
- ATL 0.2.09
- ActiveAuras 0.2.04
- Dynamic-Effects-SRD 4.1.10
- _CodeMirror 5.58.3-fvtt3
- _mathjs 7.5.1-fvtt2
- _sortablejs 1.10.2-fvtt1
- about-time 0.1.66
- combat-enhancements 0.1.8
- combat-utility-belt 1.4.0
- condition-automation 2.2.34
- dae 0.2.59
- dnd5e-helpers 1.10.1
- foundry-combat-focus 1.4.0
- itemacro v1.3.2
- lib-wrapper 1.3.5.0
- midi-qol 0.3.93
- times-up 0.1.5
- tokenmagic 0.4.4

**Summary:**
When adding an Actor who has an Active Aura feature to combat the active effect for the aura is properly enabled. When removing the Actor's Token from combat, the Active Aura's effect is not removed.

**Notes:** Have only tested with Aura of Protection (DAE) so far.

**Screenshot of Relevant Console Error:**
![image](https://user-images.githubusercontent.com/21691862/112675318-64c95f00-8e3d-11eb-9e22-e843c014e1bc.png)

**Comment by kandashi** [comment]
Noted, fixed for 0.2.05
