### ISSUE TITLE
Incompatibility with the "Token Replacer" mod

### ISSUE THREAD

**Issue by Juanfrank** [kandashi/Active-Auras#131]
Hello.-

Apparently there's an incompatibility between the AA mod and the Token Replacer mod. When AA is active, Token Replacer isn't in the Module Settings nor does it show up in the Token Configuration window, as if it were disabled. As far as I can remember, the two of them used to work fine back a few patches ago. I noticed it stopped working since I didn't notice my tokens being replaced.

I used the "Find the Culprit!" mod to identify AA as the cause of this issue.

Steps to reproduce:

1. Have Token Replacer active with whatever combination of modules, except AA. Notice it works and shows up in the Module Settings window.
2. Activate AA and check the Module Settings. Token Replacer isn't there anymore.
3. Disable AA. Token Replacer shows up in the Module Settings again.

I can't speculate on what the cause would be since I believe they address such different stuff.

**Comment by Juanfrank** [comment]
I have figured out the issue and it's on Token Replacer's mod side. Seems like a redeclaration of the "debug" variable. It's done in Token Replacer with a let debug = false; which is also done in https://github.com/kandashi/Active-Auras/blob/86587b7071ba6476bef7a283a124bbe837970c69/src/aura.js#L219.

As I believe it's a shared issue it could be fixed on either side. However I'll delete it on Token Replacer's side internally as it has less frequent updates.

**Comment by kandashi** [comment]
Ill leave this open to remind me to fix too

**Comment by kandashi** [comment]
Fixed as off 0.2.05
