### ISSUE TITLE
Issue when applying a special expiry to aura effects

### ISSUE THREAD

**Issue by Bfrench6** [kandashi/Active-Auras#133]
Having an aura with a special expiry (screenshot 1) does not seems to have the intended effect, as the applied effect on the target tokens does not expire and instead produces an error, see screenshot 2.

![image](https://user-images.githubusercontent.com/12520977/114107215-8ba47e00-989e-11eb-9639-5dd4b95cbe3c.png)

![image](https://user-images.githubusercontent.com/12520977/114107109-51d37780-989e-11eb-85e3-a986f70aeb9a.png)

**Comment by kandashi** [comment]
Yes, this will be going out in the next patch

**Comment by kandashi** [comment]
closes by #134
