### ISSUE TITLE
Getting errors about not being able to read the property started

### ISSUE THREAD

**Issue by Zamrod** [kandashi/Active-Auras#135]
I'm getting thousands of these errors from Auras:
aura.js:873 Uncaught (in promise) TypeError: Cannot read property 'started' of undefined
    at Function.MainAura (aura.js:873)
    at aura.js:559

No combats are listed in the combat tracker

**Comment by ExileofBrokenSky** [comment]
Same

**Comment by kandashi** [comment]
Should be fixed as of 0.2.08
