### ISSUE TITLE
Spirit Guardians Spell

### ISSUE THREAD

**Issue by uLotUu** [kandashi/Active-Auras#138]
Spirit Guardians doesn't work properly. If you set "if(args[0] === "on")" enemies will roll for damage only first time the aura is applied. For some reason the aura is not turning off at the end of each turn. The only way to correct it is to set "if(args[0] === "each")". This however doesn't do damage on the application. So I guess it should be "if(args[0] === "each" || args[0] === "on")"

**Comment by kandashi** [comment]
I'll have a look
