### ISSUE TITLE
Only 1 aura effect on template

### ISSUE THREAD

**Issue by uLotUu** [kandashi/Active-Auras#142]
Since the last update only the first effect on an item is transfered to a template. Others are ignored.

**Comment by kandashi** [comment]
Make sure that you have re-taken the AA ApplyEffectsToTemplates macro and are using the most up to date version. This shouldnt occur with that version and the latest AA version

**Comment by uLotUu** [comment]
I've unistalled the moudle completly, then deleted all spells with  AA ApplyEffectsToTemplates on them (they didn't work otherwise). I've installed the module again and created new spells. Now they work correctly.

**Comment by kandashi** [comment]
Good to know, thanks for the update
