### ISSUE TITLE
Effects doubled when 2 GMs are linked

### ISSUE THREAD

**Issue by Pipizio** [kandashi/Active-Auras#143]
Hi, I noticed that when there are 2 masters connected in the same world the auras are doubled.
It's normal?

**Comment by kandashi** [comment]
This should not be an issue with the latest branches, can you confirm what version you are on?

**Comment by Pipizio** [comment]
Foundry 0.7.9 
Dnd 5e latest version

**Comment by kandashi** [comment]
What about active auras version?

**Comment by Pipizio** [comment]
0.2.10 i think the latest version

**Comment by kandashi** [comment]
I cannot replicate this, can you give me a list of steps that you take that causes the issue

**Comment by Pipizio** [comment]
Then the problem also exists with "the protective aura of the paladin in the compendium"
I try to be as clear as possible, when there are 2 GMs linked it is shown in the GIF is duplicated.

![test exhaust 3 (1)](https://user-images.githubusercontent.com/75280178/115392907-62aab400-a1e1-11eb-89ae-688962819e7b.gif)

**Comment by kandashi** [comment]
Can you try with *just* Active Auras enabled. If that does not work PM me an invite to your game through discord and I'll have a look

**Comment by kandashi** [comment]
Closing as lack of info.
