### ISSUE TITLE
Combat on non-active scene

### ISSUE THREAD

**Issue by Deuterazamus** [kandashi/Active-Auras#145]
Using a spell that has an aura-template in a combat on a non-active scene throws this error:

```
aura.js:1103 Uncaught (in promise) TypeError: Cannot read property 'current' of undefined
    at Function.UpdateToken (aura.js:1103)
    at Function.UpdateAllTokens (aura.js:960)
    at Function.MainAura (aura.js:899)
    at aura.js:560
```
 
Similar error occurs also if pressing "next turn" on the combat tracker

**Comment by kandashi** [comment]
Auras on a non-active scene will not be tracked, I will remove this error message however

**Comment by Deuterazamus** [comment]
Can I suggest a notification when an aura is skipped on non-active scene? 
Might spare you from a ton of support requests

**Comment by kandashi** [comment]
it would be a *lot* of notifications, which is why its not implemented
