### ISSUE TITLE
"Collate Auras called on a non-viewed scene" when it is the viewed scene

### ISSUE THREAD

**Issue by dmaneyapanda** [kandashi/Active-Auras#147]
I am on the active scene, and I drop a spell with an active aura.

The creatures in the aura get targeted, but I get a foundry yellow warning message across the top saying "Collate Auras called on a non-viewed scene.  Aura will be applied when scene is viewed." or something to that effect.

If I then switch to another scene and switch back, the auras get applied as expected.

**Comment by kandashi** [comment]
Which spell are you using, a AA compendium one or a homemade. They have to be applied in a *very* specific way, and if not done correctly it will try to update on linked tokens on a non-viewed scene, hence the error

**Comment by dmaneyapanda** [comment]
It is "homemade", in that it is a copy of what I now see must have been an earlier implementation of Darkness that you provided in your compendium.  I made a few cosmetic changes to it (changed the icon, gave the effect an icon).  But comparing now, I see that you've moved some of the code from an Item Macro to a separate AA Apply Effects to Template macro, which confuses me a little... do we now also have to import these macros into game?  Isn't that what Item Macro is supposed to help avoid?

Anyway, I'll attach my Darkness export here.  Nope, no I won't, can't attach json I guess.

**Comment by kandashi** [comment]
The macro can be placed in an item macro if you wish, I provided them externally for transparency and ease of use for those without item macro
