### ISSUE TITLE
'Aura Targets' value appears to be flipped

### ISSUE THREAD

**Issue by simsm** [kandashi/Active-Auras#154]
Active-Auras: 0.2.11
Foundry: 0.7.9

When choosing 'Allies' for the 'Aura Targets' option, if the intended target actor is a PC, the active aura is only added to PC tokens with a 'Token Disposition' of 'Hostile'.
Similarly, when choosing 'Enemy' for the 'Aura Targets', the active aura is only added to tokens with a 'Token Disposition' of 'Friendly'.

**Comment by kandashi** [comment]
It is based on the source token, if they are "hostile" then an "allied" aura will apply to "hostile" tokens

**Comment by simsm** [comment]
Ahh, I understand now. Thanks for the explanation!
