### ISSUE TITLE
Spirit Guardians macro typos

### ISSUE THREAD

**Issue by Tatonker** [kandashi/Active-Auras#155]
Hey, sorry to do this, but I've noticed a couple of typos in the Spirit Guardians macros for the 'flavour text' elements.

Guardians is spelled incorrectly in 2 places and there is a superflous } at the end of the DC flavour text.

![image](https://user-images.githubusercontent.com/70360365/118348048-71dd0300-b4fc-11eb-8040-80f7722646c2.png)

![image](https://user-images.githubusercontent.com/70360365/118348009-36423900-b4fc-11eb-8742-838b5bf8e99b.png)

I'm loving what this module can do, now just need to figure out how to use it to its fullest (still struggling with that 'Blinded' condition on Fog Cloud.

Thanks,

Tatonker

**Comment by Tatonker** [comment]
The extra } for the DC check may be across more than just that Spirit Guardian macro, I've just checked the following macros and its there as well;

1) Incendiary Cloud
2) Grease

**Comment by kandashi** [comment]
This should be fixed in the latest version of AA, at least the spirit guardians one

**Comment by Avitale34** [comment]
I am trying to get Active Aura version of Spirit Guardians spell to work but I am not having any success, is there something I need to do beside import the AA-Spirit Guardians Macro and the spell?
