### ISSUE TITLE
Feature Request: Add compatibility to Pathfinder system(s)

### ISSUE THREAD

**Issue by Hjard** [kandashi/Active-Auras#156]
Would it be possible to add compatibility to PF1e and or PF2e systems at some point? Module is interesting and since PF1e is similar in game mechanics to Dnd5e there also are a lot of "aura" effects that would profit equally as much from automation by your module.

**Comment by kandashi** [comment]
PF2 does not use Active Effects that I know of, and the devs are working on their own system I believe
