### ISSUE TITLE
Multiple copies of Auras granted from tokens in inactive scenes, and multiple issues of effects when moving tokens

### ISSUE THREAD

**Issue by evilcj925** [kandashi/Active-Auras#16]
Tokens seem to grant auras multiple times when left on inactive scenes, stacking the effect. 

there also seems to be an issue where the effect is granted twice when moving the token in to range, but get corrected on a subsequent move. video attached

https://user-images.githubusercontent.com/67852506/103951085-e937fb80-50f2-11eb-8c08-61cc14f31dfc.mp4

**Comment by kandashi** [comment]
I can neither replicate the duplicating auras over multiple scenes, or the double status effect unfortunatly...

**Comment by eddyk1** [comment]
I was having the same problem. Let's see if with the updated version this still occurs.

**Comment by krysztalzg** [comment]
I'm having similar issue, one token have 2 auras of range 10 ft, other token when moved into range gets one effect (the texts are updating on the sheet so the effects are probably replacing each other) then on next move he gets 2nd effect. Then after moving out he loses one effect and on another move loses second effect. Really strange

**Comment by kandashi** [comment]
Can you upload a copy of the actor with the auras?

**Comment by krysztalzg** [comment]
Hey, here's quite clean world with this issue being replicable:
[vanilla.zip](https://github.com/kandashi/Active-Auras/files/5875511/vanilla.zip)
And recording of issue itself:
https://youtu.be/qkHzy4py1fQ

**Comment by kandashi** [comment]
thanks for the report, this should now be fixed as of #55

**Comment by krysztalzg** [comment]
I've checked new version and it looks to work perfectly fine, I'm not running any games this week, but will give it a shot next weekend

**Comment by kandashi** [comment]
this seems to be fixed for now, so i'll close this (finally 😄  )
