### ISSUE TITLE
Active Auras - dae - Libwrapper conflict

### ISSUE THREAD

**Issue by Jonwh25** [kandashi/Active-Auras#161]
Using latest active auras and latest dae.  Getting a conflict from libwrapper.

![image](https://user-images.githubusercontent.com/60674327/120883780-01258580-c594-11eb-97cc-5a57a081438a.png)

![image](https://user-images.githubusercontent.com/60674327/120883796-0f73a180-c594-11eb-95a6-855c2006a464.png)

**Comment by hwfwalton** [comment]
+1
Seeing the same warning
