### ISSUE TITLE
Active Auras - Token Magic FX not resetting properly

### ISSUE THREAD

**Issue by Schwelmer** [kandashi/Active-Auras#162]
When a Token is affected by a Paladin's Aura of Protection (and the token gets the benefits as well as the Token Magic FX effect), and then the Paladin or Token moves away, the Token Magic FX doesn't get removed, only the benefit. If the token once again enters the Paladin's Aura afterwards the benefit/aura once again applies properly, but also stacks the Token Magic FX effect onto it once more.

![activeaura-bug](https://user-images.githubusercontent.com/40150880/120887055-2399bc00-c5f1-11eb-8481-78adcea3b4f6.gif)

I'm not sure if this needs to be addressed by Token Magic FX or Active Auras.

**Comment by kandashi** [comment]
how are you applying the TMFX effect?

**Comment by waaldiigam** [comment]
Hi, got the same. Token FX  effect just stays on tokens. Aura is removed correctly (it doesn't show it anywhere in character sheet).

**Comment by Schwelmer** [comment]
@kandashi This is how it is applied:
![image](https://user-images.githubusercontent.com/40150880/121003672-15cd6d80-c78e-11eb-8c15-5b8af652f345.png)
As for the versions (sorry should have included them):
Foundry 0.8.6
dnd5e 1.3.3
AA 0.3.0 (socketlib 1.0.6)
DAE 0.8.12 (libWrapper 1.6.2.0)
TMFX 0.5.1

I turned all other addons off just to be safe, but no change.

**Comment by kandashi** [comment]
This is a DAE bug, is replicatable without Active Auras
