### ISSUE TITLE
Module Throws setting error in 8.6 due to missing furnace settings

### ISSUE THREAD

**Issue by SR5060** [kandashi/Active-Auras#164]
Not sure if this causes actual impacts but looks like it's due to line 162 in tokenmagic.js

**Comment by kandashi** [comment]
Imma need more info that that

**Comment by SR5060** [comment]
![image](https://user-images.githubusercontent.com/85184490/121050393-270e7e00-c77e-11eb-8516-1979f98834cc.png)

this error occurs on load

**Comment by SR5060** [comment]
I think the furnace settings were removed with the 8.6 update since it was broken up into separate modules, so the current furnace module is just used to point to the new modules

**Comment by kandashi** [comment]
Well thats nothing to do with Active Auras

**Comment by SR5060** [comment]
Active auras is pointing to a setting that no longer exists. that's all

**Comment by SR5060** [comment]
oh wow, I just realized I was looking at the wrong module. sorry!
