### ISSUE TITLE
Creature type detection not working - DND5e 1.3.5

### ISSUE THREAD

**Issue by jasonleach-dev** [kandashi/Active-Auras#170]
Foundry 0.8.7
DND5e 1.3.5
Monsters imported via DNDBeyond Importer (but seems to be the same for the system SRD monsters so I *think* this is related to the system)

Line 58 of AAhelpers.js is failing - canvasToken.actor?.data.data.details.type.toLowerCase() 
the details property is an object, not a string.
{
    "value": "undead",
    "subtype": "",
    "swarm": "",
    "custom": ""
}
I assume this is the new DND5e system structure, but could be DNDBeyond.

**Comment by kandashi** [comment]
That is indeed the new 1.3.5 structure, I'll take a look
