### ISSUE TITLE
Bug fix for IgnoreSelf and aura radius

### ISSUE THREAD

**Issue by yahavatar** [kandashi/Active-Auras#173]
Foundry: 0.8.8
DnD5e: 1.3.6
Active-Auras: 0.3.03

I was struggling to figure out the issue with "Ignore Self" flag not working when setting up auras in CUB. I tracked down the issue to Active-Auras. Specifically, to the AAhelper.js file:

![image](https://user-images.githubusercontent.com/780527/123561806-9de4d880-d778-11eb-87f1-ed9aa05649e4.png)

By changing the line:
        if (actor.id == change.effect.data.origin?.split('.')[1] && change.effect.data.flags?.ActiveAuras?.ignoreSelf) {
To:
        if (actor.id == change.effect.parent.id && change.effect.data.flags?.ActiveAuras?.ignoreSelf) {

I can now use CUB + Active-Auras to apply negative buffs to opponents and not have the player actor be affected negatively.

I think the original code was throwing a silent error because once it was fixed I also started to see shadowy templates appear, both circular and square. In the pic below, I have the radius set to 10 feet:

![image](https://user-images.githubusercontent.com/780527/123561874-0338c980-d779-11eb-8830-fe77a05af56e.png)

When I move the actor near an enemy, the negative strength effects definitely propagate correctly. However, the glow effect shows up on both the enemy and the player token:

![image](https://user-images.githubusercontent.com/780527/123561916-43984780-d779-11eb-9897-71a8d4137b60.png)

Here are the effects from CUB's Condition lab:

![image](https://user-images.githubusercontent.com/780527/123561998-e2bd3f00-d779-11eb-9d54-af5aa2f7fbd4.png)

This fix is a shot in the dark and I hope it leads to an eventual, official fix. YMMV and you might destroy the world if you use it... don't blame me!

yah.

**Comment by kandashi** [comment]
AA has not been updated for dnd 1.3.6, but when updating for that I'll have a look for this

**Comment by yahavatar** [comment]
The bug has been around for a while. Negative buffs haven't worked for me since 0.8.6, I think. Maybe longer.

**Comment by kandashi** [comment]
Interesting. Thanks for looking into this so rigously 👍

**Comment by yahavatar** [comment]
No problem. This is a truly great module and adds a bunch to our playing experience. When you have several or many actors/monsters with auras, it's tough to manually figure out who's got what affecting them without this.

Your code is impressive. When updates quit breaking great modules, all our lives will be better... lol.

**Comment by kandashi** [comment]
So looking at this again, `change.effect.parent.id` would always return true, as this just references the owner of the effect which is always true. 
I've relized I purge some of the flags (including ignoreSelf) so I can just check for that instead

Update should go out in 0.3.05
