### ISSUE TITLE
Feature Request: Reverse / Negative Auras

### ISSUE THREAD

**Issue by napolitanod** [kandashi/Active-Auras#175]
Hello!

I understand you are busy. Throwing this out there as a request for far future. It would expand the use cases for aura to have a toggle that lets the aura function in reverse. In other words, instead of the aura emanating out from one token, the token carrying the aura gains effects based on it's proximity to other tokens (which don't have the aura). An example use case is pack tactics in DND5e, which grants a creature advantage on attacks if it is in proximity to an ally.

This may not be in the scope of active-auras, but it seems adjacent to the functionality and would make use of many of the existing aura fields within the form so it may feel more seamless to users being included as part of this module than in another.

Thank you for your consideration and the work you put into your modules!
Dan

**Comment by kandashi** [comment]
Its theoretically possible, I'll sketch it in for down the line

**Comment by mkemp** [comment]
@napolitanod I've simulated pack tactics (or similar) by having the aura ignore the owning token, but apply to other appropriate tokens of the same type. Maybe that pattern would work without a new feature?

**Comment by kandashi** [comment]
Im marking this as out of scope for this module
