### ISSUE TITLE
Constant Console Spam Post Combat

### ISSUE THREAD

**Issue by KonteiKeisei** [kandashi/Active-Auras#176]
**Describe the bug**
Once combat is ended, Aura effects are not cleared, and the following is spammed in the console everytime the source or impacted tokens are moved: Active Auras not active when not in combat

**To Reproduce**
1. Start Combat
2. Move source token so that aura is applied to at least one destination token
3. end combat
4. performance degrading spam begins

**Expected behavior**
Auras are cleared and no such console spam occurs

**Screenshots**
![image](https://user-images.githubusercontent.com/49371326/126918565-b88502de-075a-4e1e-aadb-d84f402f9588.png)

**Environment:**
 - Browser [edge chromium]
 - Foundry Version [0.8.8]
 - Module Version [0.3.03]

**Additional context**
`
<html>
<body>
<div role="treeitem" aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(255, 255, 255); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-anchor" style="box-sizing: border-box; min-width: 0px; min-height: 0px; float: right; text-align: right; max-width: 100%; margin-left: 4px;"><span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-secondary); text-decoration: underline; cursor: pointer; word-break: break-all;"><br class="Apple-interchange-newline">aura.js:22</span> </span><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--override-console-warning-text-color);">Active Auras not active when not in combat</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(255, 255, 255); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(41, 50, 61); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | MainAura | @ | aura.js:22
-- | -- | -- | --
  | CollateAuras | @ | collateAuras.js:58
  | async function (async) |   |  
  | CollateAuras | @ | collateAuras.js:45
  | (anonymous) | @ | AAhooks.js:90
  | setTimeout (async) |   |  
  | (anonymous) | @ | AAhooks.js:88
  | async function (async) |   |  
  | (anonymous) | @ | AAhooks.js:78
  | _call | @ | VM33834:4
  | callAll | @ | foundry.js:153
  | callback | @ | foundry.js:8880
  | (anonymous) | @ | foundry.js:8850
  | _handleUpdateEmbeddedDocuments | @ | foundry.js:8850
  | _updateEmbeddedDocuments | @ | foundry.js:8739
  | async function (async) |   |  
  | _updateEmbeddedDocuments | @ | foundry.js:8728
  | update | @ | backend.mjs:153
  | async function (async) |   |  
  | update | @ | backend.mjs:151
  | updateDocuments | @ | document.mjs:366
  | updateEmbeddedDocuments | @ | document.mjs:532
  | moveMany | @ | foundry.js:19708
  | _handleMovement | @ | foundry.js:812
  | (anonymous) | @ | foundry.js:781
  | setTimeout (async) |   |  
  | _onMovement | @ | foundry.js:781
  | _handleKeys | @ | foundry.js:558
  | _onKeyDown | @ | foundry.js:511

</span></div>
</body>
</html>`

**Comment by kandashi** [comment]
Well it was an intentionall log, but it wasnt meant to impact performance that much :/

**Comment by kandashi** [comment]
closed in 0.3.05, will only log if debug setting is enabled

**Comment by Ikabodo** [comment]
I think I found a bug connected to this fix.

It seems (and I tried this with a minimum number of modules active) that if you turn the debug of it changes the behavior. As in if the debug is turned off, active auras remains active outside combat.
