### ISSUE TITLE
Crashes after enabling an aura

### ISSUE THREAD

**Issue by magroader** [kandashi/Active-Auras#178]
**Describe the bug**
I installed the mod and then set up an Aura of Protection for our paladin to add +Cha mod to everyone's saves (as described in the Active Auras readme). That seemed to work.

I then enabled a TokenMagic effect. I chose "save roll" in the list (I didn't know what it was). Turns out, is was very goofy animation that I wouldn't want to use.

After moving the paladin around a few spaces to see that the animation was running on allies, I went to change the TokenMagic effect. When I tried to open the Effects pane, Foundry hard crashed (I lost my connection to the server, and had to relaunch the game).

After that, every time I launched the game and logged into it with my Gamemaster user, Foundry would crash after a few seconds in the same way, even if I didn't move.  I tried removing the Aura of Protection effect entirely, but it STILL crashed after a few seconds even without the effect.

**To Reproduce**
I don't have a reliable, consistent repro at this time. (I am having separate(?) performance issues logging into the game in the first place, so I didn't want to spend time on that.)

**Expected behavior**
Active Auras should not cause performance issues or crashes.

**Environment:**
 - **OS:** Ubuntu
 - **Browser** Brave
 - **Foundry Version** 0.8.8
 - **Module Version** 0.3.05
 - **All Modules Disabled:** No
 - **Module List if no:** 

(plus Active Auras, which I just removed)
```
About Time v1.0.4;
Active Token Lighting v0.2.16;
Ambient Doors v2.2.5;
Arbron's Compendium Tools v0.4.3;
Arbron's Context Menu Library v0.2.1;
Arbron’s Improved HP Bar v2.0.4;
Automated Animations v0.5.28;
Automatic Journal Icon Numbers vv1.3.3;
Better Ambient Loop by Blitz v1.1.2.1;
Better Rolls for 5e v1.6.8;
Better Text Drawings v1.1.0.1;
Cautious Gamemaster's Pack v0.2.10;
Character Actions List dnd5e v4.1.0;
Combat Enhancements v1.0.2;
Combat Utility Belt v1.6.1;
Compact DnDBeyond 5e Character Sheet v0.17.0;
Compendium Browser v0.5.0;
Compendium Folders v2.3.5;
Conditions for D&D 5e v0.4.10;
Context Convenience v2.0.0;
DFreds Convenient Effects v1.8.6;
DFreds Droppables v1.2.8;
DF Settings Clarity v3.2.1;
Disable Mouse Wheel Control for Sliders v1.1.5;
DNDBeyond NPC Sheet v1.3.3;
Dynamic Active Effects SRD v6.0.01;
Dynamic effects using Active Effects v0.8.43;
FXMaster v1.2.1;
GM Notes v0.4.1;
Health Estimate v2.6.3.2;
Illandril's Token HUD scaler v1.4.2;
Initiative Double Click v1.0;
JB2A - Patreon Complete Collection v0.2.0;
Keybind Lib v0.3.2;
Legendary Training Wheels v0.2.0;
Less Fog v0.8.5;
lib - Color Settings v2.6.1;
Library: Chat Commands v1.3.3;
libWrapper v1.8.0.0;
Magic Items v2.1.2;
Mag Roader's Journal Sorting v1.1.0;
Monk's Little Details v1.0.35;
Monk's TokenBar v1.0.49;
Move Audio Controls v0.2.0;
Multilevel Tokens v1.5.2;
Nap Time (5E) v0.1.1;
Narrator Tools v0.61;
Navbar Tweaks v1.0.5.0;
Next Up v0.1.08;
OneJournal v1.5.1;
Perfect Vision v2.8.1;
Permission Viewer v0.8.9;
Pings v1.2.12+0.8.6;
Playlist Importer v1.7.0;
Quick Insert - Search Widget v2.4.7;
Quick Status Select v1.7.0;
Scene Transitions v0.1.3;
Selective Show v1.2;
Sequencer v0.6.4;
Settings Extender v1.1.6+0.8.6;
Short Rest Recovery for 5E v0.4.2;
Show Art v1.1.4;
Show Drag Distance v2.2.3;
Show Notes v0.5;
Simple Calendar vv1.3.28;
Skill Customization for D&D5e v2.3.0;
socketlib v1.0.8;
Split Journal v1.1;
Tidy UI - Game Settings v0.1.24;
times-up v0.8.12;
Token Auras v1.14;
Token HUD Wildcard v1.4.0;
Token Info Icons v2.3.2;
Token Magic FX v0.5.2.1;
Wall Cutter v1.1.1;
Zoom/Pan Options v1.6.5;
```

**Comment by kandashi** [comment]
Ive removed a copyright infringing module from your list, and I cant look into this further untill you can confirm either console errors, reproduction steps or replicate with only AA + depenacies active
