### ISSUE TITLE
[BUG] @item passed as an object

### ISSUE THREAD

**Issue by DarKDinDoN** [kandashi/Active-Auras#179]
**Describe the bug**
When dae macro execute contains the `@item` flag, a token entering the aura doesn't get the actual item data, but a string `"[object", "Object]"`:

![image](https://user-images.githubusercontent.com/1687854/129594305-c4f5728a-d0ca-44eb-b165-eed7dd3eca68.png)

**To Reproduce**
1. Setup a dae execute macro on each turn with an aura effect
2. Start a combat
3. setup the effect
4. get another combatant turn (not the token with the effect applied on it)
5. Check the result

**Environment:**
 - OS: Windows
 - Browser: Chrome
 - Foundry Version: 0.8.8
 - Module Version: DAE 0.8.43 & AA 0.3.05
 - All Modules Disabled: Yes

**Comment by kandashi** [comment]
Can you provide a item json that causes this error
