### ISSUE TITLE
Request: Example of how to set this up

### ISSUE THREAD

**Issue by JLtheking2** [kandashi/Active-Auras#18]
Hey there! The mod sounds awesome and I would like to try it out. Is it possible for you to provide an example of how to set up this mod to work? Perhaps in the mod description or by providing an example Actor or Item in the compendium?

[I tried to work it out myself but couldn't manage to figure it out.](https://www.reddit.com/r/FoundryVTT/comments/kta58a/how_do_i_apply_tokenmagic_effects_via_dae/?)

How do I achieve the result as shown in the gif in the description? 

Many thanks and great mod!

**Comment by kandashi** [comment]
Some guide work is needed yes
