### ISSUE TITLE
Custom Creature Type not Registering on AA

### ISSUE THREAD

**Issue by King-of-Braves** [kandashi/Active-Auras#182]
**Describe the bug**
When a custom creature type is listed the "Check creature type" field it does not register when the aura is active. This happened after upgrading from 3.05 to 3.06.

**To Reproduce**
Give a Token a custom creature type. 
Add the same custom creature type to the "Check type field." 
Activate the aura.

**Expected behavior**
The aura should be active on the creature with the custom creature type.

**Environment:**
 - OS: Windows 7 (yeah)
 - Foundry Version 0.8.9
 - Module Version 3.06
 - All Modules Disabled: No
 - Module List if no: 
About Time
Active Token Lighting
Active-Auras
Advanced Macros
Combat Utility Belt
Dynamic effects using Active Effects
Item Macro
lib - Color Settings
libWrapper
Midi QOL
socketlib
The Furnace

**Additional context**

**Comment by kandashi** [comment]
I cannot replicate this issue, screenshots of the setup would help, or any error messages
