### ISSUE TITLE
`@@` syntax is not computing target's property value as expected.

### ISSUE THREAD

**Issue by unsoluble** [kandashi/Active-Auras#184]
**Describe the bug**
`@@` syntax is not computing target's property value as expected.

**To Reproduce**
1. Use an effect value like `@@attributes.movement.walk` in an aura.
2. Make the aura affect another token.
3. Observe other token's effect has interpreted this as `@25`, for example — pulling `@attributes.movement.walk` from the aura's originating actor.

**Comment by kandashi** [comment]
Will go out in next release this evening

**Comment by DarKDinDoN** [comment]
Hey, quick question about this. Is it smt specific about Active-Auras the `@@` notation? Or can this be used without AA and only with DAE?

**Comment by kandashi** [comment]
I didnt realize that DAE had changed its syntax tbh
