### ISSUE TITLE
[FEATURE] Don't disable at 0 HP when 0 MAX.

### ISSUE THREAD

**Issue by abstract** [kandashi/Active-Auras#191]
I'm creating active auras for spell effects. A specific example is D&D 5e _flaming sphere_. I'm using it to create a token fx fire effect on affected creatures within 5 feet. I represent the sphere as an NPC sheet with token that players can control, and I add the aura to an active effect. Pretty standard stuff.

I want to give the NPC hp of 0/0, but I also want to disable auras at 0 hit points. I chose one, which was to not disable at 0 hit points.

Suggestion: Do not deactivate at 0 hit points if they have 0 maximum hit points as well.

**Comment by BlackMoons** [comment]
Suggestion for abstract: Set the token race to 'Notarget' and IIRC midi qol template attacks won't target it. Then it can have 1HP.

**Comment by kandashi** [comment]
Added a check for 0 max hp
