### ISSUE TITLE
Moonbeam broken

### ISSUE THREAD

**Issue by weepingminotaur** [kandashi/Active-Auras#193]
Does not auto-roll saving throw at start of monster turn. Returns this error:

combatUpdate.js:63 updating each  7 6 Combatant {_token: TokenDocument5e, _actor: Actor5e, resource: 63, apps: {…}, _sheet: null, …}
(anonymous) @ combatUpdate.js:63
_call @ VM2312:4
callAll @ foundry.js:153
callback @ foundry.js:8976
(anonymous) @ foundry.js:8915
_handleUpdateDocuments @ foundry.js:8915
_updateDocuments @ foundry.js:8803
async function (async)
_updateDocuments @ foundry.js:8794
update @ backend.mjs:154
async function (async)
update @ backend.mjs:151
updateDocuments @ document.mjs:366
update @ document.mjs:448
nextTurn @ foundry.js:13423
_onCombatControl @ foundry.js:33545
(anonymous) @ foundry.js:33465
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
combatUpdate.js:63 updating each  7 6 Combatant {_token: TokenDocument5e, _actor: Actor5e, resource: 54, apps: {…}, _sheet: null, …}

aura.js:201 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'current')
    at Function.UpdateToken (aura.js:201)
    at Function.UpdateAllTokens (aura.js:112)
    at Function.MainAura (aura.js:43)
    at AAhooks.js:58

**Comment by weepingminotaur** [comment]
Have verified this with all modules disabled except AA, Midi, DAE, and dependencies. Casting Moonbeam returns this error:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'current')
    at Function.UpdateToken (aura.js:201)
    at async Function.UpdateAllTokens (aura.js:112)
    at async Function.MainAura (aura.js:43)

**Comment by kandashi** [comment]
are you in combat?

**Comment by weepingminotaur** [comment]
Yes.
