### ISSUE TITLE
Multiple Creature Type detection via one aura?

### ISSUE THREAD

**Issue by paulcheeba** [kandashi/Active-Auras#194]
**Describe the bug**
Adding more than one creature type in the Check Creature Type field yields not effect on creatures in the list while adding only one creature does work as intended.

**To Reproduce**
enter either "aberration, celestial, elemental, fey, fiend, undead" or "aberration/celestial/elemental/fey/fiend/undead' and the aura will have no effect on any creatures at all except maybe the source token.
This default text indicates it should work:
![image](https://user-images.githubusercontent.com/75949480/141660941-a9ed5005-d116-4dbd-aa32-e8ffde5f38e3.png)

**Expected behavior**
Expected aberration, celestial, elemental, fey, fiend, or undead creatures to have the effect applied while in range.

**Screenshots**
![image](https://user-images.githubusercontent.com/75949480/141660882-427b608c-9493-4b2e-90ef-32b3b26a458a.png)

**Environment:**
 - OS: windows
 - Browser chrome
 - Foundry Version 0.8.9
 - Module Version 0.3.08
 - All Modules Disabled: No - i don't think this would help
 - Module List if no: 
 Active Modules:
----------
About Time v1.0.4;
Ace library v1.3.0;
Active-Auras v0.3.08;
Active Token Lighting v0.2.17;
Advanced Macros v1.12;
Advanced Spell Effects v0.6.3;
Animation Preview v1.0.3;
Automated Animations v0.6.56;
Automated Evocations - Companion Manager v1.4.6;
Better Roll Tables v1.8.5;
Better Target v0.1.18;
Better Text Drawings v1.1.0.1;
Changelogs v0.4;
Combat Utility Belt v1.7.2;
CommunityLighting by Blitz v0.4.7;
Compendium Folders v2.3.53;
Conditional Visibility v0.1.4;
Custom Token Animations v0.2.51;
Deprecated Modules v1.1.4;
DF Architect v3.1.0;
DF Chat Enhancements v3.4.1;
DF Curvy Walls v3.2.1;
DFreds Droppables v1.3.1;
Dice So Nice! v4.2.2;
Dice Tray v1.2.1;
DnD5eShopRollTables v1.0.0;
Drag Ruler v1.8.2;
Drag Upload (Get Over Here!) v2.0.0;
Dynamic Active Effects SRD v6.0.01;
Dynamic effects using Active Effects v0.8.64;
Easy Exports v0.6.1;
Easy Target v2.12;
Foundry Community Macros v0.48.0;
Foundry Community Tables v0.17.0;
FXMaster v1.2.1;
GM Notes v0.4.1;
Hey, Wait! v0.6.2;
Initiative Double Click v1.2;
Inline Webviewer v3.1.0;
Inventory+ v0.3.5;
Item Containers v1.8.13;
Item Macro v1.5.5;
Jack Kerouac's Animated Spell Effects v0.6.8;
JB2A - Patreon Complete Collection v0.3.0;
Keybind Lib v0.3.4;
Less Fog v0.8.6;
Let Me Roll That For You! v1.20;
lib - Color Settings v2.8.1;
Library: Chat Commands v1.3.3;
Library: DF Hotkeys v2.3.5;
LIB Targeting v0.1.1;
libWrapper v1.10.8.0;
Loot populater NPC | 5e v0.3.1;
Loot Sheet NPC 5e v3.2.3;
Lordu's Custom Dice for Dice So Nice v0.33;
Macro Editor v1.0.9;
Macro Folders v1.2.23;
Magic Items v2.1.2;
Merge Walls v0.8.1;
Midi QOL v0.8.82;
Midi SRD v0.1.03;
Monk's Active Tile Triggers v1.0.35;
Monk's Little Details v1.0.38;
Monk's Scene Navigation v1.0.18;
Monk's Wall Enhancement v1.0.3;
Multilevel Tokens v1.5.2;
Not Your Turn! v1.1.5;
SRD: Enhanced v1.40.2;
PnP - Pointer and Pings! v2.3.3;
Quick Insert - Search Widget v2.5.0;
Ready Set Go! - A Ready Check Module v1.2.3;
Roll From Compendium v1.1.2;
RollTable Buttons v1.2.4;
Sane Magical Item Prices Compendium v0.5.0;
Select tool everywhere v1.2.0;
Sequencer v1.2.2;
Simple Calendar vv1.3.75;
Simplefog - Manual Fog of War v0.1.18;
SmallTime v1.13.6;
socketlib v1.0.9;
Spellbook Master v1.0.4;
Spells, Items, and Features Toolkit v0.4.3;
Splatter v2.6;
Split Journal v1.1;
Tagger v1.1.5;
Tasha's Summons v1.0.0;
The Furnace v2.6.1;
Tidy5e Sheet v0.5.17;
Tidy UI - Game Settings v0.1.28;
times-up v0.8.23;
Token Action HUD v1.3.20;
Token Attacher v4.2.1;
Token Auras v1.14;
Token Info Icons v2.3.4;
Token Magic FX v0.5.2.1;
Token Mold v2.13.1;
TorchLight v0.10.0;
Universal Battlemap Importer v2.2.0;
Warp Gate v1.9.1;
Weather Control v4.0.3;

Inactive Modules:
----------

Cleaner sheet title bar v1.3.3;
Over Engineered Maps v0.1.0;
Target Enhancements v1.0.0;
Title Bar Text Remover v0.1.0;

**Additional context**

**Comment by KaosticW** [comment]
@kandashi How was this fixed? I'm facing the same issue.

**Comment by kandashi** [comment]
See the v9 milestone that isn't released yet
