### ISSUE TITLE
[Feature] Re-calculate before saving throws

### ISSUE THREAD

**Issue by Weggeley** [kandashi/Active-Auras#195]
**Is your feature request related to a problem? Please describe.**
My paladins Aura of Protection remains an active effect on the other tokens post combat. This sets up for a problem when asked to roll a saving throw outside of combat.

**Describe the solution you'd like**
I'd like to see an option where the aura is checked again at saving throws, so that the correct tokens may get the aura.

**Describe alternatives you've considered**
I have been considering writing a macro that enumerates all controlled tokens, except my paladin, and remove the active effect from them manually.

**Comment by kandashi** [comment]
This isnt supposed to happen, and will be tracked in #197
