### ISSUE TITLE
[V9] Error thrown when clicking next turn in combat tracker

### ISSUE THREAD

**Issue by DarKDinDoN** [kandashi/Active-Auras#202]
**Describe the bug**
There is an error thrown on each new turn of a combat in V9.

**To Reproduce**
1. Just create an encounter and start it 
2. then click next turn several times

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/1687854/148095813-ad36ac78-dffe-4b4d-92e4-460ba13b131f.png)

**Environment:**
 - OS: Windows
 - Browser Chrome
 - Foundry Version 9.238
 - Module Version 0.3.08
 - All Modules Disabled: Yes

**Comment by kandashi** [comment]
Use the v9 branch or dont use AA for now

**Comment by DarKDinDoN** [comment]
@kandashi should I pull the branch directly? Or can I download a release somewhere?
No release specific to the V9 branch if I'm not mistaken.

**Comment by kandashi** [comment]
You'll have to manually zip and install

**Comment by DarKDinDoN** [comment]
Confirmed this not an issue on V9 branch
