### ISSUE TITLE
[V9] Error thrown on combat end

### ISSUE THREAD

**Issue by DarKDinDoN** [kandashi/Active-Auras#203]
**Describe the bug**
Assuming a combat started with a PC and a NPC.
If the combat ends on the turn of the **logged-in** PC, while an NPC has a condition attached to it, foundry throws an error

**To Reproduce**
1. Open up foundry as a GM **AND** as a player with a character
2. Start a combat with that player character and some random NPC (player shouldn't have rights on that NPC)
3. Add a random condition to the NPC token ("blind" for example)
4. Go to player's turn
5. End the combat
6. Check the player view to see the error

**Expected behavior**
No error or message on the player client.

**Screenshots**
![image](https://user-images.githubusercontent.com/1687854/148106405-7b7ca12a-494f-47c9-99e4-a799caf6d7fa.png)
![image](https://user-images.githubusercontent.com/1687854/148105888-e35ab7c3-9dd0-41a5-8592-e000c5feac5a.png)

**Environment:**
- OS: Windows
- Browser Chrome
- Foundry Version 9.238
- Module Version 0.3.08
- All Modules Disabled: Yes

**Comment by kandashi** [comment]
See #202

**Comment by DarKDinDoN** [comment]
@kandashi Hi, installed V9 branch. Issue is still there.
I think you can reopen this issue.

**Comment by kandashi** [comment]
Fixed again
