### ISSUE TITLE
[BUG] Dropping/Deleting a token on the canvas into an Aura Area doesn't apply the aura effects

### ISSUE THREAD

**Issue by DarKDinDoN** [kandashi/Active-Auras#206]
**Describe the bug**
- Dropping a token within an aura doesn't apply the aura until the token is moved on the canvas
- Deleting a token with an aura won't delete the effect on the linked actor

**To Reproduce**
1. Setup an Active Aura on the canvas
2. Drop a token into this area, the token doesn't inherit the effect
3. Now move that same token, and the Aura effect is applied
4. Delete this token, and the linked actor sheet still has the effect applied

**Environment:**
 - OS: Windows
 - Browser Chrome
 - Foundry Version 9.242
 - Module Version 0.4.02
 - All Modules Disabled: No
 - Module List if no: DAE

**Comment by kandashi** [comment]
Cannot replicate this, please enable debug mode and screenshot the console after following the same steps

**Comment by DarKDinDoN** [comment]
@kandashi Hello,

Sorry, forgot about the basic information.
That's actually DnD 5e with DAE under the hood.

I found the issue, it's really really weird.
Basically (DAE + MidiQol + self apply an effect on item use):
- If item === trinket. Item must be equipped for the effect to be active
- If item !== trinket (like food), Item doesn't have to be equipeed for the effect to be active

Demo video: https://user-images.githubusercontent.com/1687854/163981809-c24c36d9-53df-485d-98d6-d496d645d968.mp4

**Comment by DarKDinDoN** [comment]
@kandashi 

**Video showcasing the bugs:** https://user-images.githubusercontent.com/1687854/163985643-45e9358f-b019-4085-9fa5-823125b39a22.mp4
**Exported aura:** [fvtt-Actor-silence-aura.json.txt](https://github.com/kandashi/Active-Auras/files/8512217/fvtt-Actor-silence-aura.json.txt) (just remove the .txt extension, because Github doesn't want me to upload .json files)
**Character used in the video:** Just one of the default 5e Character located in the *Starter Heroes* compendium

**Comment by kandashi** [comment]
Should be fixed in next release

**Comment by DarKDinDoN** [comment]
@kandashi just tested this. Deletion is OK, dropping an actor within an aura doesn't work.
