### ISSUE TITLE
[BUG] Applied effect is shown as "Suspended" with multiple side effects

### ISSUE THREAD

**Issue by DarKDinDoN** [kandashi/Active-Auras#207]
**Describe the bug**
For an applied Aura Effect:
- An effect is applied as "Suspended" on a target actor/token
- If something like macro.CUB is supposed to be applied with the effect (DAE effect), then it is not
- Also, the  option "Apply Active Effect icon to affected tokens?" doesn't seem to be working as well

**To Reproduce**
1. Create an Active Aura
2. Drop a token and check effect tab in corresponding actor sheet 

**Environment:**
 - OS: Windows
 - Browser Chrome
 - Foundry Version 9.242
 - Module Version 0.4.02
 - All Modules Disabled: No
 - Module List if no: DAE/CUB

**Comment by kandashi** [comment]
This should be fixed in the latest patch
