### ISSUE TITLE
Auras do not apply "correctly" to tokens larger than 2x2.

### ISSUE THREAD

**Issue by the-real-orson** [kandashi/Active-Auras#213]
**Describe the bug**
Auras do not apply correctly to tokens that are larger than 1x1 grid units.  Inconsistent application of Aura and aura is missing entirely when only one of a 3x3 (or presumably larger) creature's grids is inside the aura radius.

**To Reproduce**
1. Place a token on the map with a grid size of 2x2 (a large creature).
2. Add an effect to the above token's actor with an aura.  Make the aura radius 2.9 (I'm using 5 ft. for my grid scale). Note: I'm using 2.9 to encompass the maximum possible area without creating the aura effect on a 1x1 token adjacent to the source token.
3. Place a huge creature (3x3 token). 
4. Move this tokens in and out of the aura radius.
5. When the 3x3 token is overlapping the aura with only 1 grid, the aura does not apply.
6. When the 3x3 token is overlapping the aura with only 2 of it's grids, the aura may or may not apply/persist.

**Expected behavior**
A grid unit encompassed by the token is inside a grid unit encompassed by the aura, the aura effect is applied.

**Screenshots**

**Environment:**
 - OS: windows 10
 - Browser Chrome
 - Foundry Version 9.255
 - Module Version 0.4.02
 - All Modules Disabled: Yes
 - Module List if no: 

**Additional context**
I realize that the issue in question is because of the imperfections of circles in a square/gridded world and center to center measurement.  I guess you could also look at this as a feature request rather than a bug report...Is there an alternative to center to center method of calculating the aura?  I would think most players expect something like a Moonbeam or Flaming Sphere to apply effect to any token that has a grid inside the aura radius.

**Comment by the-real-orson** [comment]
![1](https://user-images.githubusercontent.com/97677751/158425834-e4e19fb9-6e45-4cbd-8279-5c8131485fe7.png)
![2](https://user-images.githubusercontent.com/97677751/158425865-4eb7e29e-5798-4a22-9678-7dc552f819ea.png)
![3](https://user-images.githubusercontent.com/97677751/158425890-02cb813d-dda8-418e-931a-8566e32da30b.png)
![4](https://user-images.githubusercontent.com/97677751/158425916-9efd5ed3-d9d2-4220-8f9c-e1b4167a7dc5.png)
![5](https://user-images.githubusercontent.com/97677751/158425933-ff44aed8-0562-4269-b5ad-c2a34bde8a3c.png)
![6](https://user-images.githubusercontent.com/97677751/158425952-7c5fb503-357a-4636-ace8-73dac9bde419.png)
![7](https://user-images.githubusercontent.com/97677751/158425967-4912e84d-93e3-41c5-a7dd-9ed245f15380.png)

**Comment by Draco18s** [comment]
Yeah, [measureDistance](https://github.com/kandashi/Active-Auras/blob/main/src/measureDistances.js#L24-L42) only handles the center and the four corners.

Would need to adjust the points-to-check to include the intermediary squares.

**Comment by the-real-orson** [comment]
Right, I feel you on that...but based on what I'm seeing in game in my fourth picture, the aura isn't applying to the Dire Troll even though the centerpoint of the Dire Troll's bottom right grid is inside the Aura radius.  Based on the code you linked to above, it looks like it should work, however it isn't working in game.  When, the Aura is over the top right grid square of the Dire Troll, the Aura applies properly,but not on the bottom right.  I'm still unclear on why there is a difference, even less so after pondering the way the array of points is generated.

**Comment by Draco18s** [comment]
Not sure either.

**Comment by kandashi** [comment]
The issue was in a pre-"intense calculation" bounding check that only used the target actors x/y not width/height
