### ISSUE TITLE
Compatibility with DF Template Enhancements

### ISSUE THREAD

**Issue by YuanRamirez** [kandashi/Active-Auras#216]
**Problem**
Activating DF Template Enhancements, which changes a few things about how templates are drawn, makes auras not work on templates. Why is DFTE important? It fixes template rotation for square templates, can snap templates to grid intersections, does automatic targeting that is also intergrated with MidiQOL – basically, if set up right, templates drawn with DFTE active behave the way they should (at least for dnd5e).

**Solution**
DF Template Enhancements has functionality to target tokens inside the AOE of the template. Maybe you could utilize that to find the affected tokens after all the drawing is done? I'm not sure.

**Alternative**
Maybe this is an issue with DF Template Enhancements and not active auras. Both modules work fine on their own.

**Additional context**
I'm honestly not sure what exactly breaks. There are no errors in the console and according to AuraMap the effect gets applied to the template as expected. Unsurprisingly, auras attached to tokens work just fine.

**Comment by kandashi** [comment]
I dont think its an issue with DF templates, there is a bug with the way template auras are measured atm

**Comment by YuanRamirez** [comment]
Seems to work with the newest update
