### ISSUE TITLE
Ignore self doesn't seem to work

### ISSUE THREAD

**Issue by TogaParty** [kandashi/Active-Auras#218]
**Describe the bug**
Ignore self does not allow the effect to be applied to the caster/source.

**Comment by TogaParty** [comment]
I doubt it's a factor, but I'm testing under SW5e, and using an ability built using a direct copy of the D&D5e ability: Aura of Protection

**Comment by kandashi** [comment]
Define "dosnt work"

**Comment by TogaParty** [comment]
Effect is not applied to the caster.

**Comment by kandashi** [comment]
Thats what "ignore self" means

**Comment by TogaParty** [comment]
Right - what I'm saying is that it doesn't matter how you have this value set, the caster is ignored.
