### ISSUE TITLE
Mod not working?

### ISSUE THREAD

**Issue by JLtheking2** [kandashi/Active-Auras#22]
Tried out the mod with your new instructions but I seem to be unable to get it to work. [Video of what I tried.](https://www.youtube.com/watch?v=8nLWBihucWA)

Added an active effect to an existing feature and gave it an aura of 10 feet. For the effect I chose the token magic glow aura. When the feature is added to a character sheet the glow effect is applied correctly. But the aura doesn't seem to transfer the effect to surrounding tokens?

Or perhaps I am misinterpreting the instructions again. Sorry again for the trouble.

Mods Active:
TidyUI, TidySheet, Active Auras, DAE, Token Magic FX.

Cheers 👍

**Comment by kandashi** [comment]
Do you get any errors in the console ?

**Comment by JLtheking2** [comment]
![image](https://user-images.githubusercontent.com/48344299/104104212-adaf5400-52e1-11eb-8699-686c1759bdd0.png)

I do get this error when i remove the feature ("Aura of Protection") from the wolf, as seen in the video.

No errors when i add the feature granting the aura to the wolf, and none when i move the wolf close to the bigger wolf.

**Comment by kandashi** [comment]
could you PM me an invite to your game and make an assistant account so I can locally test?
