### ISSUE TITLE
SW5e: "Remove Auras on death" doesn't remove aura effects when a token reaches zero HP

### ISSUE THREAD

**Issue by TogaParty** [kandashi/Active-Auras#220]
**Describe the bug**
SW5e: "Remove Auras on death" doesn't remove aura effects when a token reaches zero HP

**To Reproduce**
1. Setup an aura
2. Move another token into range so it's affected.
3. Set to zero HP for the token emitting the aura

**Comment by kandashi** [comment]
What error do you get

**Comment by TogaParty** [comment]
No console output.  Aura is not removed.

**Comment by kandashi** [comment]
Should be fixed now
