### ISSUE TITLE
If multiple characters have the same aura effect, the math goes wonky (+4 to +44???)

### ISSUE THREAD

**Issue by GambetTV** [kandashi/Active-Auras#222]
Essentially I have two Paladins in my group, and both have Aura of Protection. For some reason when an ally is within the radius of both Paladins, instead of getting a +4 and +4 from each of them (+8 total), it gets added as +44.

Also, this brings up a secondary issue, which there may be no fix for, but there are some effects in the game which do not stack, but there doesn't seem to be a way to avoid that with the module currently, unless I'm missing something.

**Comment by kandashi** [comment]
Change the value to `+@abilities.cha.mod` and that will fix
