### ISSUE TITLE
Ignore self setting does not work - enabled or not, the effect is not applied to the caster

### ISSUE THREAD

**Issue by TogaParty** [kandashi/Active-Auras#224]
**Describe the bug**
Filing this again.  The previous item was closed, but was not resolved.  This setting does nothing it doesn't matter if it's enabled or not, the effect is not applied to the caster either way.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - Foundry Version [e.g. 0.8.8]
 - Module Version [e.g 0.1.42]
 - All Modules Disabled: Yes/No
 - Module List if no: 

**Additional context**

**Comment by kandashi** [comment]
I cannot replicate this on dnd5e with the provided info. I cannot dedicate more time to troubleshooting other systems, expecially those not avaliable via the foundry official list
