### ISSUE TITLE
Possible incompatibility with BetterRolls5e

### ISSUE THREAD

**Issue by zacdemon** [kandashi/Active-Auras#23]
There seem to be some incompatibilities with BetterRolls5e. I haven't had a chance to thoroughly test them so I'm not sure if this is on your end or RedReign's. I tested this with the Aura of Devotion demo in the Readme. The Aura seems to behave as indented for tokens other then the carrier, but for the token carrying the aura when a roll is made I receive this error. It seems to behave fine when BetterRolls is disabled.
![image](https://user-images.githubusercontent.com/22028379/104107335-57162b80-5289-11eb-9fe4-334debea3836.png)

**Comment by kandashi** [comment]
Known issue with DAE and Better Rolls release version, though the dev branch should fix this I believe. The reason it only occurs on the Aura Token is that that is the only token that actaully has the efffect value as (@abilites.cha.mod) the reciving tokens have that parsed out to a flat number
