### ISSUE TITLE
Add support for scale value function of dnd5e 1.6.0

### ISSUE THREAD

**Issue by 413120** [kandashi/Active-Auras#230]
**Is your feature request related to a problem? Please describe.**
No, There is no issue with how it currently functions, this would just be a quality of life improvement.

**Describe the solution you'd like**
dnd5e 1.6.0 added a function for class advancements to add/change features by class level for characters. The relevant bit is [this part right here about scaling values](https://gitlab.com/foundrynet/dnd5e/-/issues/1492#scale-value). This allows, for example, adding an identifier for the scale of certain functions, such as @scale.paladin.aura-of-protection for paladin's aura of protection radius. 

**Describe alternatives you've considered**
The current method for achieving this is simply editing the aura's radius in the effect manually upon hitting the level for it to change. Really, this isn't the biggest issue, but this change would be a small quality of life change.

**Additional context**
[An example of the scale value function for aura of protection](https://i.imgur.com/6h6FYXM.png)

**Comment by sharkbruhaha** [comment]
yes please!

**Comment by rayd99** [comment]
Renewing the call for this feature. A scale value for Paladin auras is a perfect example.

**Comment by MrPrimate** [comment]
This is in v0.5.6
