### ISSUE TITLE
Add a per Aura "Walls Block Aura" option

### ISSUE THREAD

**Issue by Jeznar** [kandashi/Active-Auras#231]
I have run into a need to have an aura penetrate walls while another aura should be blocked by walls.

The global setting works great to control wall penetration across the world, but it doesn't allow granular control.

<img width="607" alt="Active_Auras_and_Walls" src="https://user-images.githubusercontent.com/95548360/174071299-12307fc3-2248-42e2-9650-e4a52e6b8312.png">

I think it would make sense to allow a per aura setting to override the global wall penetration setting.
 
<img width="588" alt="Screen Shot 2022-06-16 at 8 39 48 AM" src="https://user-images.githubusercontent.com/95548360/174071940-c15a379c-56f6-4750-a6ce-64a40ec116f4.png">

**Comment by MrPrimate** [comment]
In v0.7.7
