### ISSUE TITLE
Foundry 10 - 'Drawing Shape' has already been detected

### ISSUE THREAD

**Issue by TheBalzan** [kandashi/Active-Auras#239]
Hello team, I have received the following error after upgrading to Foundry 10.

Uncaught SyntaxError: Identifier 'DrawingShape' has already been declared (at templateDetection.js:1:1)
[Detected 1 package: ActiveAuras]
    at templateDetection.js:1:1
(anonymous) @ templateDetection.js:1

**Comment by CharlesHunter** [comment]
Can confirm issue persists with Foundry Version 10 build 284 using DnD5e - Fifth Edition System v2.0.2
```
Uncaught SyntaxError: Identifier 'DrawingShape' has already been declared (at templateDetection.js:1:1)
[Detected 1 package: ActiveAuras]
    at templateDetection.js:1:1
(anonymous) @ templateDetection.js:1
```

**Comment by kandashi** [comment]
None of my modules are yet updated for v10. Do not expect quick updates as I have very little time on my hands right now

**Comment by CharlesHunter** [comment]
Understood.  I appreciate the work you do maintaining these. :)
