### ISSUE TITLE
Macros with DAE variables not executing

### ISSUE THREAD

**Issue by CeaneC** [kandashi/Active-Auras#24]
Hi there, I'm trying to have a macro fire when a token enters an aura, applying an effect to that token. I'm doing this in the same way I'd set up a normal DAE macro execution effect, with an attribute key of `macro.execute`, change mode of `custom`, and effect value of `MacroName @target`. However whenever a token enters the aura, I get a warning message saying "No macro + found".

If I'm not mistaken this line is the issue: https://github.com/kandashi/Active-Auras/blob/main/src/aura.js#L223
It seems to be geared specifically for adding variable values to other attributes, but breaks down when used for macro execution. Is there another way I should be trying to do this?

**Comment by kandashi** [comment]
Ahh shoot yeah. I can add a check for this
