### ISSUE TITLE
v10 Compatability?

### ISSUE THREAD

**Issue by SabreRunner** [kandashi/Active-Auras#244]
I didn't see anywhere mentioned if this is v10 compatible. Is that in the plans?

**Comment by shecrio** [comment]
https://github.com/kandashi/Active-Auras/issues/239#issuecomment-1235379875
Not soon but planned for "eventually"

**Comment by MrPrimate** [comment]
If you are looking for a v10 version, the open PR's to support it have been built into the following package till it is merged:

- Active Auras: https://github.com/MrPrimate/Active-Auras/releases/download/v0.4.22/module.json
- Active Token Effects/Lighting: https://github.com/MrPrimate/Active-Token-Lighting/releases/download/v0.4.02/module.json
