### ISSUE TITLE
Error when disabling an AE and "Disable scrolling text for auras" is enabled

### ISSUE THREAD

**Issue by kristianserrano** [kandashi/Active-Auras#251]
**Describe the bug**
There is an error when disabling an AE and "Disable scrolling text for auras" is enabled.
`Cannot redefine property: isSuppressed`

**To Reproduce**
1. Enable "Disable scrolling text for auras"
2. Enable and disable an Active Effect with an aura
3. AE's are not removed and error occurs (see screenshot below)

**Expected behavior**
AE should be removed from respective Actors.

**Screenshots**
![Screenshot 2022-11-16 at 11 25 56 PM](https://user-images.githubusercontent.com/1796189/202355253-00232010-d273-4e4d-9420-53b133fe9939.png)

**Environment:**
 - OS: MacOS Ventura
 - Browser: Chrome
 - Foundry Version: 10.290
 - Module Version: 0.5.1
 - All Modules Disabled: No
 - Module List if no: socketlib, libwrapper

**Additional context**
SWADE system

**Comment by MrPrimate** [comment]
Ah, it looks like there was an odd error catch statement for 5e which means I had not detected a change in behaviour in the Foundry Scrolling Text suppression.

**Comment by MrPrimate** [comment]
This should be resolved in v0.5.2
