### ISSUE TITLE
Error when disabling "Auras in combat"

### ISSUE THREAD

**Issue by kristianserrano** [kandashi/Active-Auras#252]
**Describe the bug**
Disabling auras in combat results in an error.
`ActiveAuras.CollateAuras is not a function`

**To Reproduce**
1. Disable "Auras in combat"
2. See error in console.

**Expected behavior**
Things still _seem_ to function normally

**Screenshots**
![Screenshot 2022-11-16 at 11 41 28 PM](https://user-images.githubusercontent.com/1796189/202357396-3e2b552c-91b1-4c9b-8779-0fd0a62a1907.png)

**Environment:**
- OS: MacOS Ventura
- Browser: Chrome
- Foundry Version: 10.290
- Module Version: 0.5.1
- All Modules Disabled: No
- Module List if no: socketlib, libwrapper

**Comment by MrPrimate** [comment]
Thankyou for the report, this is a straightforward fix

**Comment by MrPrimate** [comment]
This should be resolved in v0.5.2
