### ISSUE TITLE
When an aura expires, a bunch of "The key xiUnKSwiLHy3pYuR does not exist in the EmbeddedCollection Collection" errors appear. 

### ISSUE THREAD

**Issue by nirurin** [kandashi/Active-Auras#254]
**Describe the bug**
I have a spell which applies an aura effect to all nearby creatures for 60 seconds. When the aura expires, the effects all delete (which is correct) but it also spawns a list of red errors on the page and in the console. They are all:

The key xiUnKSwiLHy3pYuR does not exist in the EmbeddedCollection Collection

...errors, but each has a different key string (I assume it's one for each creature that was in the aura). 

**To Reproduce**
1. Create effect with aura with a duration
2. Apply it
3. Let the duration expire   (This is important, as deleting the effect ends it all without errors. It's only when the time expires that the errors seem to pop up)
4. Profit

**Expected behavior**
The same, but without all the error message spam

**Screenshots**
attached. ![untitled](https://user-images.githubusercontent.com/3751273/209419789-5b6054ef-de49-4af7-a12a-52bbe3bbb930.png)

**Environment:**
 - OS: windows11
 - Browser: Edge
 - Foundry Version 10.281
 - Module Version 0.5.3
 - All Modules Disabled: No (this module won't work if everything is disabled)
 - Module List if no: 
 About Time
Active Token Effects
Active-Auras
Advanced MAcros
Dynamic Active Effects
Item Macro
libwrapper
MidiQOL
SImple Calendar
SmallTime
socketlib
TimesUP

(It can probably function with a couple of these off, I just kept all the 'time' and 'calendar' based ones on as I needed to be able to skip the time ahead to end the duration faster.)

Edit:
I notice there's also an error in the console (shown in picture) : 

ERROR CAUGHT in RemoveAppliedAuras TypeError: Cannot read properties of undefined (reading '_onDelete')

which seemed potentially relevant.

**Comment by MrPrimate** [comment]
I have a potential fix for this, but it's still in testing with a few people, as it might break active effect removal in some areas. Please can you install the module from https://github.com/MrPrimate/Active-Auras/releases/download/v0.5.3/module.json and see if this branch resolves this issue for you?

**Comment by nirurin** [comment]
I am now on 0.5.3, but it doesn't seem to have made any obvious difference. I'm still getting all the red error spam popups.

**Comment by nirurin** [comment]
Is there anything else I can try?

**Comment by MrPrimate** [comment]
I'm having trouble replicating this - can you upload an item with the effect on?

**Comment by nirurin** [comment]
[fvtt-Item-sounds-of-silence-(s).zip](https://github.com/kandashi/Active-Auras/files/10312483/fvtt-Item-sounds-of-silence-.s.zip)

Here's an export. The aura is set up on this in an item macro, for completely unrelated reasons (these spells are being cast in an unusual way). But the error is that same as when it was set up the normal way too. 

In fact just in case, here's another spell I made with the same errors, but set up the more normal way. 

[fvtt-Item-tempo-slow.zip](https://github.com/kandashi/Active-Auras/files/10312504/fvtt-Item-tempo-slow.zip)

The issue only happens when you cause the effect to end from the duration running out. If you manually end it by deleting the source effect, the rest all ends cleanly.

**Comment by MrPrimate** [comment]
Please can you check version v0.5.4 and see if this resolves your issue.

**Comment by nirurin** [comment]
> Please can you check version v0.5.4 and see if this resolves your issue.

Seems to be fixed on my end! Thankyou good sir
