### ISSUE TITLE
Aura Ends When Used

### ISSUE THREAD

**Issue by TogaParty** [kandashi/Active-Auras#261]
**Describe the bug**
When attempting to setup a persistent effect such as an aura that grants a bonus to saves, the effect ends when a save is rolled.  The effect should be persistent, or there should be an option to make it persistent.

**To Reproduce**
1. Setup an aura that grants a bonus to saves:
-DAE flags.midi-qol.optional.NAME.save.all, add, @abilities.cha.mod
-Aura Yes, Allies, Radius = 5, -, -, -, check token height, -, Apply Active Effect icon to affected tokens? -, -
2.  Move an allied token in range, and make a save
3. Make another save on the allied token

**Expected behavior**
The charisma bonus should be applied to both saves.  It is applied to the first allied save, but that ends the effect..

**Screenshots**

**Environment:**
 - OS: Self hosting, raspberry pi x64.  Windows client
 - Browser Multiple
 - Foundry Version 9.280
 - Module Version Latest as of 1/3/23
 - All Modules Disabled: No
 - Module List if no: Lengthily

**Additional context**

**Comment by MrPrimate** [comment]
You're creating an "optional" effect on the target, which behave slightly different, try using `system.bonuses.abilities.save` instead.
