### ISSUE TITLE
Not seeing any settings for Active Auras in Foundry v10

### ISSUE THREAD

**Issue by HiTGray** [kandashi/Active-Auras#262]
**Describe the bug**
Just that. I go to token settings and there is no Auras tab and there are no Aura settings under appearance. I'm in the 5e world.

**To Reproduce**

**Expected behavior**
I expected to click on token settings and see options for creating an Aura.

**Screenshots**
<img width="496" alt="Screen Shot 2023-01-18 at 9 59 18 AM" src="https://user-images.githubusercontent.com/123014909/213267617-ff5e0ad5-ee74-4e59-8d3d-e76a8c5fd919.png">

**Environment:**
 - Foundry Version [Version 10 - Build 291]
 - Module Version [v0.5.5]
 - All Modules Disabled: Yes
 - Module List if no: 

**Additional context**
I've tried it with all modules disabled and not disabled. Makes no difference.

**Comment by MrPrimate** [comment]
This module does not do that, you apply an effect to the actor/token that is set as an aura effect. If you previously saw an aura here, this will be the following module: https://foundryvtt.com/packages/token-auras

**Comment by HiTGray** [comment]
Oh gosh. Whoops. Thanks!
