### ISSUE TITLE
Effects do not spread to nearby tokens within the aura

### ISSUE THREAD

**Issue by dkaerit** [kandashi/Active-Auras#266]
**Describe the bug**
I have a problem with active auras and it is that the effects are not extended to the nearby tokens as it should happen. To check if it was just me, I was comparing with my friends, with the same configurations and the same active Foundry modules, and yes, it extends to them in the way that I am going to explain in the following steps

**To Reproduce**
1. I create the following Active Aura in the list of DFreds Action Effects (which allows you to create an Action Effect that can be applied to a token manually without it being associated with an Item)
![image](https://user-images.githubusercontent.com/24440929/217540913-60c12bdd-bd37-4c13-a3ec-c6f8148015aa.png)
2. I apply the Action Effect to a token but the nearby ones do not receive the icon as it should happen, so I repeat, this works for my friends
![Vídeo sin título ‐ Hecho con Clipchamp](https://user-images.githubusercontent.com/24440929/217543016-31139b12-5993-4c76-a6e5-e7e5ac078a8f.gif)

**Expected behavior**
It was expected that the Action Effect "Test" icon would also appear in the other nearby tokens, which was an indicator that they were receiving the bonus, in my case they neither receive the bonus provided by the Action Effect nor are they marked with the icon, because the ction Effect is not propagating nearby ones

**Environment:**
 - OS: Windows 11
 - Browser: Microsoft Edge 109.0.1518.78
 - Foundry Version 10.291
 - Module Version Active Auras 0.5.6
 - All Modules Disabled: No ( It works for my friends with exactly the same active modules as me. )
 - Module List if no: 
![image](https://user-images.githubusercontent.com/24440929/217544062-8d67a779-25af-4e3d-84e6-70edac85ad42.png)
![image](https://user-images.githubusercontent.com/24440929/217544100-93ff5367-f264-4d3f-a191-daec9bfbd71a.png)

**Additional context**
I have tried both outside and inside combat and there is no way that it works for me.

**Comment by MrPrimate** [comment]
I can't replicate this - do you have "Auras in combat" checked in the active auras settings? Because this would prevent an aura from propagating if not in combat.

**Comment by dkaerit** [comment]
> I can't replicate this - do you have "Auras in combat" checked in the active auras settings? Because this would prevent an aura from propagating if not in combat.

at the end of my isuue:

> Additional context
I have tried both outside and inside combat and there is no way that it works for me.

**Comment by MacTruck3-Code** [comment]
Was this every resolved? I am running into the same issue.

**Comment by MacTruck3-Code** [comment]
> Was this every resolved? I am running into the same issue.

Upon closer inspection, when 'Aura Targets' is set to 'All' the aura is not applied to any targets. Works for other options.

**Comment by MacTruck3-Code** [comment]
> > Was this every resolved? I am running into the same issue.
> 
> Upon closer inspection, when 'Aura Targets' is set to 'All' the aura is not applied to any targets. Works for other options.

Not sure if this is it though. I mimicked one spell that isn't working with another one that is and still no effect. I will keep troubleshooting.

**Comment by dkaerit** [comment]
> Was this every resolved? I am running into the same issue.

I had to save the data folder that contains my worlds, uninstall foundry and reinstall it and it fixed it
