### ISSUE TITLE
Savage Worlds - Aura Effects Seem to Not Work 

### ISSUE THREAD

**Issue by Neurochimp** [kandashi/Active-Auras#268]
Auras do not convey their benefits or penalties if placed on certain actors in Savage Worlds. 

**To Reproduce**
Create NPC Actor with aura see below-

- I had auras work on a swarm actor from Rise of the Runelords - Extra with 0 Wounds.
- Then attempted to create ghostly actors with similar aura effect to convey haunting penalties, these did not work.
- Troubleshooted peeling back potential conflicts on the character
- Removed any effects [Undead & Resilient were adding effects to the actor] besides the aura effect & worked - other actors would gain & lose aura
- Added Wounds levels manually or via effect again to the ghostly actor and aura stopped functioning again.
- As a workaround I've made the version with working aura invisible while the ghost that can be fought separate/visible.

**Expected behavior**
Adding an aura to the actor should convey the benefits or penalties to actors within radius.

**Environment:**
 - OS: Windows
 - Browser: Firefox
 - Foundry Version v10 291 Savage Worlds 2.2.5
 - Module Version 0.5.7
 - All Modules Disabled: Yes - attempted disabling all modules - same issue; troubleshooting occurred with all enabled

**Comment by MrPrimate** [comment]
Hi, I'm not very familiar with the SWADE system - could you provide some screen shots or actor exports of the working/not working changes for me?

Thanks

**Comment by Neurochimp** [comment]
Sure. I responded to this email but not seeing it updated. I will drop in all the files I sent. The jsons are unsupported it seems. So only the pics here.
![4-Removed all effects-wounds auras show up](https://user-images.githubusercontent.com/116909768/219867793-63472327-964d-4169-98c0-ef4b8b77da37.png)
![3-Same as 2 but only one Swarm](https://user-images.githubusercontent.com/116909768/219867796-91e76213-26d5-4929-8481-2965d502e62f.png)
![2-Added Auras Not Working](https://user-images.githubusercontent.com/116909768/219867803-08cd7a21-a96a-40f9-ab92-0f4c49a18c90.png)
![1-Working Aura](https://user-images.githubusercontent.com/116909768/219867807-4791a931-4d1b-4185-bbd1-21ba3d3dac60.png)

**Comment by karolusb** [comment]
I don't know if this is your problem, but after taking a bunch of screenshots to post my own reasonably similar issue I realized that Remove Auras on death is a bit of a trap for savage worlds.  It looks for 0 hp.  Of course savage worlds counts wounds up, turning that option off fixed (one of) my problems.

**Comment by Neurochimp** [comment]
Odd. My problem definitely is tied to Wounds in some manner. I can create an actor with no Wound levels [basic NPC Extra] & place the aura on him. This will work & player actors in range will pick up the effect. If I add Resilient, Very Resilient, or make the character a Wildcard [all manners that Wounds get added to an actor] - the effect stops being picked up. It could make sense that having Wound levels may be interpreted incorrectly.

**Comment by Neurochimp** [comment]
Also should apologize to the dev here. I've been swamped with work - multitasking to get back to matters like this. The jsons I tried to send you bounced back & then wouldn't attach to the thread here.

**Comment by valdier1** [comment]
I can note, savage worlds has worked off and on, currently, I'm not sure why, but it doesn't work any longer. I hade one setup to provide a bonus to shake and it used to work ok, but stopped at some point.

**Comment by valdier1** [comment]
![image](https://user-images.githubusercontent.com/13425341/233550949-0b27a4a7-0880-43aa-8c81-b64624cd5c92.png)
![image](https://user-images.githubusercontent.com/13425341/233550988-6aa3a3ce-3508-48bc-9759-bc2016545cdb.png)

**Comment by valdier1** [comment]
Is there anything else I can add that might assist with this? It was working in the not so distant past.

**Comment by MrPrimate** [comment]
Hi, sorry for the delay, I have been looking at this over the weekend and hope to have a fix for you later this week.

**Comment by MrPrimate** [comment]
The bot had auto closed this, please can you check and let me know please if it fixes for you.

**Comment by valdier1** [comment]
I just tested this out and it definitely seems to be working. I'm seeing the icon applied to all affected tokens outside of combat. I will get to test it more thoroughly tonight during a game.

Thank you btw. You are awesome!
