### ISSUE TITLE
[Bug] no effect icon and no effect on allies

### ISSUE THREAD

**Issue by Bogus73** [kandashi/Active-Auras#27]
Hi,
a really cool addition to the game!
With the new update it stopped working for me as I wrote on Discord. Just wanted to put in her for you to see.

suggestion: Let us use webm files for the auras not only the effects from token magic. That would be awsome. Just like animated spell templates.

**Comment by kandashi** [comment]
AA does not support any non-core use of active effects.
As to it not working, can you post any errors that appear

**Comment by zacdemon** [comment]
I have experienced similar issues. From what I've gathered unless the "Apply while inactive box" is ticked the Aura wont propagate to other tokens.
![image](https://user-images.githubusercontent.com/22028379/104135779-1210f880-5360-11eb-86f5-8af746f3de37.png)

**Comment by Bogus73** [comment]
> 
> 
> I have experienced similar issues. From what I've gathered unless the "Apply while inactive box" is ticked the Aura wont propagate to other tokens.
> ![image](https://user-images.githubusercontent.com/22028379/104135779-1210f880-5360-11eb-86f5-8af746f3de37.png)

oh I will try that too. thx

**Comment by kandashi** [comment]
Fixed with 0.0.51
