### ISSUE TITLE
Aura is being applied to origin actor no matter what

### ISSUE THREAD

**Issue by LupusVentus** [kandashi/Active-Auras#270]
**Describe the bug**
I'm tryng to make an aura with blindess effect, but *ignore self* opion doensn't seem to work

**To Reproduce**
1. Create a self-targeting spell that has duration 
2. Add Blinded effect from DAE
3. Configure it so it *has* to ignore self
4. Try to use the skill

**Expected behavior**
Aura applies blinded to any character *exept* the one producing the aura

**Screenshots**

**Environment:**
 - OS: Windows 10
 - Browser Chrome
 - Foundry Version 10
 - Module Version 0.5.7
 - All Modules Disabled: No
 - Module List if no: 
 Active Modules:
----------
Active-Auras v;
Active Token Effects v;
Adequate Vision v;
Advanced Macros v;
Babele v;
Break Time v;
Chat Images v;
Combat Booster: Turn Marker, Recent Actions and more v;
Combat Utility Belt v;
DFreds Convenient Effects v;
DFreds Droppables v;
DF Scene Enhancement v;
DF Template Enhancements v;
Dice So Nice! v;
Dice Tray v;
Drag Ruler v;
Dynamic effects using Active Effects v;
Easy Target v;
Enhanced Terrain Layer v;
Forien's Quest Log v;
FoundryVTT Arms Reach v;
FXMaster v;
Grid Scaler v;
Health Estimate v;
Item Containers v;
Item Macro v;
Item Piles v;
Levels v;
lib - Color Settings v;
Library: Active effect manager v;
libWrapper v.0;
Lordu's Custom Dice for Dice So Nice v;
Maestro v;
Midi QOL v;
Midi SRD v;
Monk's Active Tile Triggers v;
Monk's TokenBar v;
Monk's Wall Enhancement v;
Multilevel Tokens v;
Music Permissions v;
Narrator Tools v;
Patrol v;
Pings v;
Plutonium v;
Plutonium Addon: Automation v;
Polyglot v;
Quick Insert - Search Widget v;
Rarity Colors v;
RRItemsTranslationTCE v;
❄️ Russian Translation | Русский перевод v15;
Settings Extender v;
Simbul's Athenaeum v;
Simbul's Cover Calculator v;
Simbul's Creature Aide v;
Simple Calendar v;
socketlib v;
Stairways (Teleporter) v;
Terrain Ruler v;
Tidy5e Sheet v;
Tidy UI - Game Settings v;
Times Up v;
Token Action HUD v;
Token Attacher v;
Token Auras v;
Token HUD Wildcard (fix) v;
Token Info Icons v;
Token Magic FX v;
User Latency v;
Visual Active Effects v;
Wall Height v;
Warp Gate v;

**Comment by MrPrimate** [comment]
This is quite strange, it seems to happen to the `macro.ce`effects, not general system/midi flags. I suspect there is something about how DAE/Midi-QoL/Convinent Effects and how it handles effect application.

**Comment by MrPrimate** [comment]
This is resolved with the latest DAE release.
