### ISSUE TITLE
Incorrect version in module.json

### ISSUE THREAD

**Issue by ishtanzar** [kandashi/Active-Auras#272]
**Describe the bug**
The module.zip file of the 0.5.7 release has a module.json file with an incorrect version specified: v0.5.7.

**To Reproduce**
Fetch https://github.com/kandashi/Active-Auras/releases/download/v0.5.7/module.zip, read module.json of the downloaded zip file and see version: v0.5.7

**Expected behavior**
module.json should have version: 0.5.7

**Comment by MrPrimate** [comment]
Should be fixed in v0.6.0
