### ISSUE TITLE
Some aura settings persist after aura box unchecked

### ISSUE THREAD

**Issue by MotoMoto1234** [kandashi/Active-Auras#274]
**Describe the bug**
While troubleshooting a midiqol issue for a user, we discovered that a past event where the user had checked the aura box and turned on a bunch of settings, and then instead of clearing/reverting, they just shut off the aura, caused the settings to somehow directly affect the active effect during midi effect transfer still.  I am attaching the offending item for you to fiddle with, but it would cause the saving throw to never roll at advantage from the affected actor unless we shut off active auras, I then discovered that the item still had active aura flags active on it still(which you can see in the attached file).  

**To Reproduce**
1. Import my attached item as a feature
2. add it to actor A with Actor B 25ft away, note that the items range is 10ft and watch when you roll it
3. Once its now uncannily on the 25ft away actor, roll a saving throw on that actor, they were ment to have advantage, they won't
4. Disable active auras and repeat the process, see how it suddenly works
5. Now enable the aura on the item, clear out the settings, and then turn off the aura again and repeat the process, its fixed.  

**Expected behavior**

**Screenshots**

**Environment:**
 - OS: Windows 10
 - Browser Chrome
 - Foundry Version 10.291
 - Module Version This happens on 0.5.7 and 0.6.0
 - All Modules Disabled: Sorta, had to have midi enabled
 - Module List if no: Midi, socketlib, dae, libwrapper, active auras

**Additional context**
I can't get the file to upload cause github doesn't like json.  Just DM me if you want the file I suppose or maybe someone can tell me a workaround.

**Comment by MrPrimate** [comment]
Fixed in v0.6.1
