### ISSUE TITLE
Error on Foundry v11

### ISSUE THREAD

**Issue by Kharmans** [kandashi/Active-Auras#275]
**Describe the bug**
The module don't let the world start.

**To Reproduce**
Just start the world with the module active on Foundry v11.

**Expected behavior**
The world to initiate.

**Screenshots**
![image](https://github.com/kandashi/Active-Auras/assets/112586547/50e7c911-dae6-4195-9404-c594c73a3afb)

**Comment by MrPrimate** [comment]
Please update to v0.6.3 where this is fixed
