### ISSUE TITLE
v 11 Unable to launch world

### ISSUE THREAD

**Issue by The-BirdGod** [kandashi/Active-Auras#276]
**Describe the bug**
Can't launch world after v11 upgrade

**To Reproduce**
1. Attempt to launch world, get error code.

**Expected behavior**
World launches

**Screenshots**
![image](https://github.com/kandashi/Active-Auras/assets/110910890/c9364cd2-de67-486f-8cea-edc5d6e792b3)

**Environment:**
 - OS: Windows 10
 - Foundry Version v11 build 300
 - Module Version 0.8.6
 - All Modules Disabled: Yes
 - Module List if no:

**Comment by MrPrimate** [comment]
You need to be running version 0.7.1 for Foundry v11, v0.8.6 doesn't exist. Please uninstall Active Auras and reinstall
