### ISSUE TITLE
v11 : Effects are not removed when token is exiting aura

### ISSUE THREAD

**Issue by InjustFr** [kandashi/Active-Auras#277]
**Describe the bug**
When tokens exit an aura, the effect is not removed in v11

**To Reproduce**
1. Create any Active Effect with an aura on a first token
2. Bring a second token in the aura, see the effect being applied
3. Move the second token out of the aura
4. See that the effect is still there on the second aura

**Expected behavior**
Effects should be cleared properly when existing the aura

**Environment:**
 - OS: iOS
 - Browser : Firefox
 - Foundry Version : latest
 - Module Version : latest
 - All Modules Disabled: No

**Additional context**
As of v11, the label property is removed and converted into a getter in favor of the name member in effects data. It seems that CONFIG.AA.Map stores the tokens without their associated methods, thus without the label getter. Later, when it's time to check if a effect should be removed in the UpdateToken function, `auraEffect.data.label` returns undefined instead of the proper name of the effect, stored in `auraEffect.data.name`

**Comment by InjustFr** [comment]
It seems there is a similar issue where at the beginning of every turn in combat or at reload, the effect is being reapplied as not properly detected

**Comment by MrPrimate** [comment]
Thanks, fixed in v0.7.2
