### ISSUE TITLE
Strange Database Error in V11 with Active Auras

### ISSUE THREAD

**Issue by SirAron111** [kandashi/Active-Auras#280]
**Describe the bug**
In v11 I am getting this error.
Failed to connect to database "ActiveAuras.Active Auras Auras": Database is not open
Failed to connect to database "ActiveAuras.Active Auras Zone Actors": Database is not open
Failed to connect to database "ActiveAuras.Active Auras Macros": Database is not open

It also seems to cause problems whenever I walk into range of an ally with an aura it applies the effect, but the effect is broken. For example, paladin aura of protection. Which could be related.

**To Reproduce**
1. Install v11 foundry
2. Install active auras
3. game will show you the error, sometimes.

**Expected behavior**
dont know not sure what the error does.

**Environment:**
 - OS: Windows 10
 - Foundry Version [e.g. v11]
 - Module Version [e.g  0.7.2]

**Comment by MrPrimate** [comment]
You are using a version of active auras that does not work on v11. Please uninstall and reinstall the module.

**Comment by SirAron111** [comment]
but that version is the latest shown on the webpage and the one i get when i install it via the foundry inbuild installer.

**Comment by MrPrimate** [comment]
Ah I see, it works here, so I suggest something has gone wrong at your end when Foundry tried to upgrade the compendium packs - I would still suggest an uninstall and reinstall.

**Comment by SirAron111** [comment]
Ok so after manually uninstalling the files of active auras and then reinstalling it seems to work. For now. A bit strange, but as long as it's working, I couldn't care less. thx.
