### ISSUE TITLE
Option to select all EXCEPT one creature type

### ISSUE THREAD

**Issue by Galphanore** [kandashi/Active-Auras#286]
**Is your feature request related to a problem? Please describe.**
Right now, you have implemented a way to apply the effect only to one specific Type. There doesn't appear to be a way to select multiple types or exclude one type. So, to make, for instance, the Aura of Shrieks of a Star Spawn Grue, I have to duplicate the effect for all the types other than Aberration.

**Describe the solution you'd like**
An option to either invert the type field (so an effect can apply to everything else) or a way to select multiple types.

**Describe alternatives you've considered**
As a workaround for now, I have created the effect I want and then duplicated it for each of the non-Aberration types. This works, but requires having 13 active auras for each Star Spawn Grue which is a bit of a performance hit.\

**Comment by zeldafreak6245** [comment]
I am encountering this exact issue as well. I tried multiple creature types in one aura with no luck. I tried separating with commas, slashes, and semi-colons with no success.

**Comment by MrPrimate** [comment]
You can do this with the custom evaluation conditions in v07.7, see the README here https://github.com/kandashi/Active-Auras#custom-evaluation-conditions for an example
