### ISSUE TITLE
Aura persisting on out of range actors

### ISSUE THREAD

**Issue by DeanYear** [kandashi/Active-Auras#287]
Using Aura of Protection on a paladin in my partner (Foundry v11, latest version of Active Aura as of 05/08/2023), the aura propagates to the correct actors (within 10ft radius), but when moving the Paladin the bonus persists incorrectly.  Aura doesn't drop off over time.

**Comment by MrPrimate** [comment]
What version exactly?

**Comment by DeanYear** [comment]
Foundry v11b307 and Active Aura 0.5.7, I tested with Foundry v11b304 always.

Thanks for the quick reply!

**Comment by MrPrimate** [comment]
What options do you have selected for the module settings for active auras?

**Comment by DeanYear** [comment]
![Active Auras Screenshot](https://github.com/kandashi/Active-Auras/assets/141497656/7f5d8ffd-b650-4198-aa88-d81f6debe7b4)

**Comment by MrPrimate** [comment]
The latest version of active auras is 0.7.4, can you uninstall and reinstall the module? Sometimes Foundry can get stuck

**Comment by DeanYear** [comment]
It worked! Foundry would only let me update to 0.7.3 but manually updating via the github release worked and now the aura is working as expected, thanks for the super quick support!
