### ISSUE TITLE
Red alert in Foundry 

### ISSUE THREAD

**Issue by Fridan99** [kandashi/Active-Auras#288]
**Describe the bug**
A Foundry error appears in red color

**Failed to connect to database "ActiveAuras.Active Auras Auras": Database is not open
Failed to connect to database "ActiveAuras.Active Auras Zone Actors": Database is not open
Failed to connect to database "ActiveAuras.Active Auras Macros": Database is not open**

Foundry v11. 307
Active-Auras 0.7.5

**To Reproduce**
Just install the Active-Aura module, and go to modules section, warnings

**Screenshots**
![1 1](https://github.com/kandashi/Active-Auras/assets/86131373/418c5b15-9840-45c0-8e09-59b77fdfdbd6)

**Environment:**
 - Foundry v11. 307

**Comment by MrPrimate** [comment]
Please can you uninstall and reinstall the module, something has gone wrong during install.

**Comment by Fridan99** [comment]
It seems that this was the error. The alert has disappeared. 

Thx
