### ISSUE TITLE
Renaming the received aura effect

### ISSUE THREAD

**Issue by JulianS-Uni** [kandashi/Active-Auras#289]
Would it be possible to rename the aura effect created on the actors effected by the aura? 

Use case:

Paladin has an aura effect called "Aura of Protection - Aura". The current behaviour is that all effected actors (allies) also get an effect called "Aura of Protection - Aura".  I would like to rename the effect received by them to "Aura of Protection".  This would allow me to automaticly add animations the the tokens with "Automated Animation" through its auto recognition feature.

**Comment by MrPrimate** [comment]
In v 0.7.6
