### ISSUE TITLE
v11

### ISSUE THREAD

**Issue by CaosFR** [kandashi/Active-Auras#291]
Hi,

Any chance for a update to the v11 ?

Thanks

**Comment by MrPrimate** [comment]
It works on v11, see the otehr issues if you're having problems: https://github.com/kandashi/Active-Auras/issues?q=is%3Aissue+is%3Aclosed+v11

**Comment by CaosFR** [comment]
Thanks for your reply, I will open issue in case of.

**Comment by MrPrimate** [comment]
It might be it's stuck on an older version, so try and uninstall and reinstall of the module

**Comment by CaosFR** [comment]
> It might be it's stuck on an older version, so try and uninstall and reinstall of the module

It was stuck, thanks !
