### ISSUE TITLE
"Ignore self" is ignored

### ISSUE THREAD

**Issue by Vogliadicone** [kandashi/Active-Auras#295]
The option "ignore self" didn't seem to work in SWADE with Toughness. The Aura is applied to the actor as well.

I set up an aura for an commander, that should apply only to the token around the actor, but not to the actor themself:
![02](https://github.com/kandashi/Active-Auras/assets/119852651/3acef632-ab9e-4420-9128-f2ecb0ba9202)
![03](https://github.com/kandashi/Active-Auras/assets/119852651/b90a00be-74f8-4bee-b6d2-228484977a59)
The auras works for the other characters around, but the Toughness is also added to the actor himself:
![01](https://github.com/kandashi/Active-Auras/assets/119852651/3178df69-6f43-437f-8a5f-a7b83c7a9e9e)

As far as I remember, that worked for me half a year ago under FVTT10 & SWADE2.4, but now it isn't. Any idea of what I might be doing wrong? If you need more data, let me know.

- Foundry VTT: 11.315 (in the OracleCloud)
- Swade System: 3.2.3
- Active Auras: 0.8.3
- Browser: Google Chrome

I can reproduce the problem in a test world with only SWADE and Active Auras.

**Comment by MrPrimate** [comment]
Reslved in v0.9.1
