### ISSUE TITLE
AA on items aren't applied to other characters

### ISSUE THREAD

**Issue by Vogliadicone** [kandashi/Active-Auras#296]
Auras in SWADE that I set up directly on a character work. But if I ad the same aura to a magic item, the aura didn't work. F.e. I gave an actor a command aura:
![2-01](https://github.com/kandashi/Active-Auras/assets/119852651/d6332a68-93d4-4e3a-bb8c-0ad7fe8bf890)
![2-02](https://github.com/kandashi/Active-Auras/assets/119852651/7ea2a1d0-91f8-46f6-80b6-393a45200d37)
And then I gave him a magic item with the same aura (I just made it Toughness +10 to be able to easily see which is which):
![3-1](https://github.com/kandashi/Active-Auras/assets/119852651/8aab35fc-0117-4939-b7ca-a485e406d6c2)
The actor himself is now under the effect of both auras (which should be ignored, but that's another [issue#295](https://github.com/kandashi/Active-Auras/issues/295)):
![3-2](https://github.com/kandashi/Active-Auras/assets/119852651/804cee14-032f-4e4b-b54f-4f1da35750b4)
But all characters around get only the effect from the AE directly on the actor and not the effect from the item:
![3-3](https://github.com/kandashi/Active-Auras/assets/119852651/f784cb08-3ae5-4ff9-99b8-6546afe79182)
![3-4](https://github.com/kandashi/Active-Auras/assets/119852651/d5128ddd-42e1-430b-a5c1-16675547a229)

I have no idea, if that's an issue for active auras or if SWADE is doing here something differently.Let me know, if you need more data or if you need infos from the SWADE developers or if I should open a ticket there.

- Foundry VTT: 11.315 (in the OracleCloud)
- Swade System: 3.2.3
- Active Auras: 0.8.3
- Browser: Google Chrome

I can reproduce the problem in a test world with only SWADE and Active Auras.

**Comment by MrPrimate** [comment]
I have pushed some changes, as it looks like SWADE has moved to non-legacy effects (https://foundryvtt.com/article/v11-active-effects/) however it still won't work, and I think these are due to a few bugs in the SWADE system, I will attempt to identify them a bit more tomorrow, in the mean time I will release my current version of Active Auras

**Comment by MrPrimate** [comment]
Resolved in v0.9.1
