### ISSUE TITLE
Console error on token movement

### ISSUE THREAD

**Issue by Saibot393** [kandashi/Active-Auras#297]
**Describe the bug**
Error message in console

**To Reproduce**
1. Have a token with an active aura in scene A
2. Let a player control said token
3. Switch to scene B as the GM
4. Let the player move the token in scene A
5. See error

**Expected behavior**
That the error does not show up

**Screenshots**
![image](https://github.com/kandashi/Active-Auras/assets/137942782/b2f3b17f-928c-4f5e-b906-bf81b523136d)

**Environment:**
 - OS: Windows 10
 - Browser: Chrome
 - Foundry Version 315
 - Module Version 0.8.4
 - All Modules Disabled: Yes

**Additional context**
The problem seems to be the missing "object" property of tokens in other/non viewed scenes.

**Comment by MrPrimate** [comment]
Resolved by #298
