### ISSUE TITLE
Effect that ignore self does not work

### ISSUE THREAD

**Issue by Enthropx** [kandashi/Active-Auras#304]
**Describe the bug**
Aura is not applied to anything if '_ignore self?_' is checked

**To Reproduce**
- Setup an active aura with '_ignore self?_' checked (like Spirit Gardians)
- Use the spell

**Expected behavior**
- Effect does not apply to the tokens when its supposed to
- If '_Ignore self?_' is unchecked, it works fine

**Screenshots**
Here is the aura tab:
![image](https://github.com/kandashi/Active-Auras/assets/84460278/92a0a3ea-e33e-4a68-b88e-a257deab0885)
And here is the result (unaffected tokens)
![image](https://github.com/kandashi/Active-Auras/assets/84460278/b99c9855-abbc-4bc4-81ee-6c6b58741ea9)
Now here's the result with '_Ignore self?_' unchecked:
![image](https://github.com/kandashi/Active-Auras/assets/84460278/e6988c88-fa41-445d-9804-8f06575f4172)

**Environment:**
 - Foundry Version 11.315
 - System dnd5e 2.4.0
 - Module Version 0.9.1
 - All Modules Disabled: No
 - Module List if no: see full list below
Active Modules:
----------
Active-Auras v;
Active Token Effects v;
Automated Animations v;
Automated Evocations - Companion Manager v;
Babele v;
Better Roofs v;
Build-a-Bonus v;
Carousel Combat Tracker v;
Chris's Premades v;
Combat Booster: Turn Marker, Recent Actions and more v;
DFreds Convenient Effects v;
Dice So Nice! v;
Dice Tray v;
DnD5e Drag Ruler Integration v;
Drag Ruler v;
Dynamic effects using Active Effects (DAE) v;
Effect Macro v;
Filepicker + v;
Force Client Settings v;
fr-FR - DND5 System v;
Hover Distance v;
Image Context v;
Item Piles v;
JB2A - Jules and Ben's Animated Assets - Free Content v;
JB2A - Patreon Complete Collection v;
Let's Trade 5e v;
Library - Color Settings v;
Library - libWrapper v.0;
Library - socketlib v;
Macro Wheel v;
Midi QOL v1;
Midi SRD v;
Module Management+ v;
Monaco Macro Editor v;
Monk's TokenBar v;
Pin Cushion v;
PopOut! v;
Quickdraw v;
Quick Insert - Search Widget v;
Sequencer v;
SmallTime v;
Smart Target v;
Splatter v;
srd-heros-et-dragons v;
Taskbar v;
Template Macro v;
TheRipper93's Module Hub v;
Tidy5e Sheet v;
Times Up v;
Token Attacher v;
Token HUD Wildcard v;
Token Magic FX v;
Token Z v;
UI - Tidy UI - Game Settings v;
Warp Gate v;
World Scripter v;

**Comment by MrPrimate** [comment]
Hmm, very odd, I'm sure this did work, as the code has been there for ages. Please try 0.9.2

**Comment by Enthropx** [comment]
It works with 0.9.2, thanks.
