### ISSUE TITLE
Aura effects aren't applied

### ISSUE THREAD

**Issue by RawrKrake** [kandashi/Active-Auras#306]
I have the following problem: 

Every time I roll an item with an active aura (even premade like AA Spiritual Guardian), I get this:

![vdvfd](https://github.com/kandashi/Active-Auras/assets/131989900/88ad4f2d-ac17-42f9-85a8-6b2c1f2915ba)

and it won't apply the aura effect to other creatures.

Foundry is on 315, AA on 0.9.2., everything is up to date. It also happens in a new world with only AA and it's dependency's turned on.

**Comment by MrPrimate** [comment]
This is coming from a template aura. Are you sure this is the error message in a new world? Can you screen shot the effect details and aura details for the aura you are trying to create. Can you also confirm the 5e system version you are using.

**Comment by DupuyT** [comment]
Is there any update on this? I am experiencing a really similar error but with different settings. I have a custom spell that applies a 10 foot aura that causes players to glow (Token Magic) and regenerates 1 HP at the beginning of the player turn when standing in the template. When adding the spell directly to the character sheet and casting as a level 1 spell, the aura functions properly, with concentration applied and the players entering in and out getting the proper active effects applied. However, the custom spell originates from an item. I use the module Magic Items, to allow the spell to be attached to the item (https://github.com/PwQt/magic-items-2). However, when the spell is cast through the item, it seems to error and not apply the dynamic effects. 
Error:
![image](https://github.com/kandashi/Active-Auras/assets/89485374/e268df29-e5e6-4dcf-bc62-4361c3a507f9)
Item and effect details:
![image](https://github.com/kandashi/Active-Auras/assets/89485374/1c58b257-32df-4da9-8048-085ffceca50a)
I am using 5e version 3.1.2

Any advice is appreciated, I can provide more info if needed too.

**Comment by MrPrimate** [comment]
Could you provide an export of the item for me?

**Comment by DupuyT** [comment]
Of course! Here is the item and spell export.
[fvtt-Item-+1-spring-quarterstaff-of-light-ohx4MmbBVrGqO4Md.json](https://github.com/kandashi/Active-Auras/files/15385835/fvtt-Item-%2B1-spring-quarterstaff-of-light-ohx4MmbBVrGqO4Md.json)
[fvtt-Item-spring-rejuvenate-W3wOEQRbaRRAej9L.json](https://github.com/kandashi/Active-Auras/files/15385836/fvtt-Item-spring-rejuvenate-W3wOEQRbaRRAej9L.json)

**Comment by MrPrimate** [comment]
Sorry for the delay on this, fixed in 0.9.12, released soon,
