### ISSUE TITLE
[BUG] When token is updated that exists on a different scene, module throws error

### ISSUE THREAD

**Issue by Haxxer** [kandashi/Active-Auras#307]
**Describe the bug**
When a token is updated that exists on a scene that is not currently active, the module throws an error on `AAHooks.mjs` on line `73`.

https://github.com/kandashi/Active-Auras/blob/main/src/lib/AAHooks.mjs#L73

This is most likely because you are trying to access `object` which is not a valid property on scene that are not active

**To Reproduce**
1. Update a token on a scene that is not active with an active aura on it
2. See error in console

**Expected behavior**
No error

**Screenshots**

**Environment:**
 - Browser: Chrome
 - Foundry Version: v11.313
 - Module Version: v0.9.2
 - All Modules Disabled: No
 - Module List if no: Item Piles, Socketlib, Libwrapper

**Comment by MrPrimate** [comment]
Please can you screen shot the error, and confirm your version, as 0.9.0 fixed this exact issue

**Comment by Haxxer** [comment]
Can confirm that it is in fact, fixed. Thanks for checking me!
