### ISSUE TITLE
Add creature subtypes to the type of creature option

### ISSUE THREAD

**Issue by YenBenGrey** [kandashi/Active-Auras#318]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
WHen I choose creature type, it works with the major creature types, however is it possible to be able to put sub-types in the box for example in my case 'humanoid(ratfolk)'

**Describe alternatives you've considered**
I can't think of an alternative

**Additional context**
N/A

**Comment by MrPrimate** [comment]
Use a custom evaluation condition, see the README here https://github.com/kandashi/Active-Auras#custom-evaluation-conditions for an example

**Comment by YenBenGrey** [comment]
So this should work for my example - 

['humanoid','ratfolk'].includes(system.details?.type?.subtype ?? system.details?.race.toLowerCase())

**Comment by YenBenGrey** [comment]
It does work, THANK YOU SO MUCH :-)
