### ISSUE TITLE
Demo macro

### ISSUE THREAD

**Issue by atleticano-snp** [kandashi/Active-Auras#37]
Hey Kandashi,

Example macro was written incorrectly (image), missing the **i**
+@abilites.cha.mod  --> +@abilit**i**es.cha.mod

![image](https://user-images.githubusercontent.com/68756964/104829337-7e549600-5851-11eb-9209-7a997320dc4a.png)

may solve it
![image](https://user-images.githubusercontent.com/68756964/104829351-af34cb00-5851-11eb-8288-a35c7422bbd1.png)

**Comment by kandashi** [comment]
😑 that's embarrassing
