### ISSUE TITLE
Suggestion: exclude self toggle

### ISSUE THREAD

**Issue by zacdemon** [kandashi/Active-Auras#38]
There are many effects throughout several game systems that have an aura that only effects creatures other then one generating it so having the option to set the aura to only effect other tokens would be helpful.

A bit further on that note it would be nice to have some kind of system that allows you to exclude or include tokens based on actor variables ex. An aura that only effects actors that are above half HP or vice versa.

**Comment by kandashi** [comment]
This is already available in the "apply while inactive" toggle
