### ISSUE TITLE
[Suggestion] Mantain a changelog

### ISSUE THREAD

**Issue by Deuterazamus** [kandashi/Active-Auras#52]
Please mantain a changelog.md or at least add changes to readme.md

I often check what is contained in each update of modules to evaluate if it's safe to update or it's better to wait a few days but with active auras I often have to resort to checking the release name or commit comments or even version code compare. While feasable it's far from being an optimal experience and requires some degree of skill in using github. Moreover commits have comments like "fix" or "duplicate fix and hidden fix v2" that aren't as immediate as a human readable, well formed changelog.

New features are also more easily referenced and documented in a changelog/readme file

**Comment by kandashi** [comment]
Noted, most of my release notes come in the release announcements channel but I will endevour to make a more accessable version

**Comment by Deuterazamus** [comment]
you might want to take a look at this:

[https://keepachangelog.com/en/1.0.0/](https://keepachangelog.com/en/1.0.0/)
