### ISSUE TITLE
@token arg does not update and gets "stuck" after 0.1.30

### ISSUE THREAD

**Issue by MS-PBS** [kandashi/Active-Auras#53]
I noticed this issue after updating.  I can consistently replicate it in the following environment:
-Foundry 0.7.9
-DnD 5e 1.2.4

Modules active:
-Active Auras 0.1.33
-DAE 0.2.39
-The Furnace 2.6 (I need this to add args to DAE effects).

The macro I'm testing this with is:
```javascript
console.log(args);
console.log(canvas.tokens.get(args[1]).data.name)
```
The effect is an item with an aura effect set up to be always active. And the DAE effect is macro.execute CUSTOM test @token

The testing procedure is simple. I move a token into the aura as a GM, and I check the console. I get the logs I'd expect. However, if I move another token into the aura, args[1] returns the id of the token I moved earlier! Same issue when I move a third token. This gets fixed if I refresh the page, but the moment I move a token into an aura. args[1] gets stuck again.

I have tested it with other AA versions, and rolling back to 0.1.30 gets rid of this issue. I hope you find this bug report useful!

**Comment by kandashi** [comment]
I cannot replicate this issue. Though I do get the macro call referencing to the token that moves, not the token that gains the aura...

**Comment by kandashi** [comment]
Ok, now I see the issue

**Comment by kandashi** [comment]
this is because in the CreateActiveEffect function at line 444 the it re-writes the original id rather than genrating new data
