### ISSUE TITLE
Aura coordenates

### ISSUE THREAD

**Issue by rinnocenti** [kandashi/Active-Auras#59]
the radius of the aura is doing a strange calculation.
my aura has a 5 radius. (in Large creature)
It was supposed to take only tokens within the radius of the large creature.
but when it is on the left and at the top, it acts right (not catching) but if it is on the right or below, the effect catches the token.
![image](https://user-images.githubusercontent.com/3178127/107128715-b5412900-689e-11eb-9a8d-165d2f7cfc9f.png)
![image](https://user-images.githubusercontent.com/3178127/107128720-c7bb6280-689e-11eb-9e54-259ea8d8623e.png)

**Comment by kandashi** [comment]
large creature measuring is an anomoly that im not quite sure how to fix. The system seems to pick a random square to measure from, and use that staticly.
