### ISSUE TITLE
Active Auras for NPCs

### ISSUE THREAD

**Issue by MSAbaddon** [kandashi/Active-Auras#60]
Hi there,
currently - if my tests are correct - the setting "Aura targets" selects if the token is Friendly or Hostile.
This unfortunately has the effect, that the aura effects are only usable for PCs, but not for NPCs, becaue a group of monsters all have their tokens set to Hostile, although they consider each other as Allies. Maybe the setting should not only check the target's flag but also the flag of the token with the aura, with the following result:

Aura targets set to Allies: Aura is active for tokens with the same flag as the caster (caster + target friendly or caster + target hostile)

Aura targets set to Enemy: Aura is active for tokens with opposite flag as the caster (caster friendly + target hostile or caster hostile + target friendly)

**Comment by kandashi** [comment]
The easy way to change this is to just change the disposition of your other tokens. Otherwise you have to individually set a flag on every token aswell as the disposition

**Comment by MSAbaddon** [comment]
I don't think I can quite follow you. Right now I either can decide if the Auras can be used for NPCs or for PCs, but not both (correct me if I'm wrong).

E.G. The player group has a paladin and fights an enemy group that also has a paladin I can either set all player characters to friendly and all NPCs to hostile with the result that only the PC paladin aura has any effect, or I set all NPCs to friendly and all PCs zu hostile and with that deactivate the PC paladin aura and activate the NPC aura.

The only other way would be, that - depending on the owner of the item (PC or NPC) - the active effect needs to manually be changed accordingly: The PCs Aura of Courage targets Allies, the NPCs Aura of Courage targets Enemies

**Comment by kandashi** [comment]
A hostile token with an "allies" aura will only effect other hostile tokens.  It counts who is allies based on the aura tokens own disposition

**Comment by MSAbaddon** [comment]
Ok, then I have to try that again.
My initial thought was that it works that way but somehow the auras didn't trigger. Maybe I did something else wrong.
Will do some testing tonight and post the update here.

**Comment by MSAbaddon** [comment]
You're right, after some more testing everything works fine. Must have done something wrong yesterday.
