### ISSUE TITLE
4x application of aura

### ISSUE THREAD

**Issue by JustinKovacich** [kandashi/Active-Auras#61]
Following the YouTube guide to setting up ActiveAuras with Devotion Aura.  I ran into a weird issue where several of the players had multiple instances of the +4 bonus, such that a roll of 3 was getting us > 30.  It was also granting the "Frightened" immunity and I could see 4 instances of that appearing on the character sheet.  

I ended up disabling the module to get around it.  The player receiving the bonus was on the other side of a wall from the person granting the aura, if that helps at all.

Using: Active-Auras Version 0.1.35, Foundry version 0.7.9, 5e version 1.2.3

**Comment by kandashi** [comment]
can you double check what version of AA you were on

**Comment by JustinKovacich** [comment]
I'm showing 0.1.35 when I go to check, and I haven't pulled any updates so I'm pretty sure that's right.  Anything else I can share?

![image](https://user-images.githubusercontent.com/32140377/107289129-8cea3380-6a32-11eb-8980-b17c690ac0c9.png)

**Comment by kandashi** [comment]
Oh sorry, I missed that you put that in the opening post. I can't do much with an isolated report, but if you can reproduce this, or screenshot any errors in the console I can investigate more.

**Comment by JustinKovacich** [comment]
Alright.  I have ActiveAuras active and I had my group of PCs saved on a map which I stored off in a compendium.   I imported the scene and loaded it, and this is the (relevant parts of the) log:

Foundry VTT | Created ActiveEffect h6YCFhwgk2aSnwEf in parent Actor MDdmNTMyYmI0NDBj
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gariland
foundry.js:30175 Foundry VTT | Deleted 8 Tokens from parent Scene HZe5TGMfJnpC1cM1
foundry.js:29917 Foundry VTT | Created ActiveEffect MoWJ84GbBw4XG0PS in parent Actor MDdmNTMyYmI0NDBj
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gariland
foundry.js:29917 Foundry VTT | Created ActiveEffect 89znSuub5o4Oy4y3 in parent Actor MDdmNTMyYmI0NDBj
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gariland
foundry.js:29917 Foundry VTT | Created ActiveEffect rUjJJHD3Z0YPcBh1 in parent Actor MDdmNTMyYmI0NDBj
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gariland
foundry.js:29917 Foundry VTT | Created 8 Tokens in parent Scene HZe5TGMfJnpC1cM1
foundry.js:2498 Foundry VTT | Error thrown in hooked function 
_call @ foundry.js:2498
foundry.js:2499 Error: No actor or token exists with id 'Z7KjdEe9s71tyx7z'
    at IdentityFlagsStrategy.getEntity (TokenHotbar.js:374)
    at IdentityFlagsStrategy.get (TokenHotbar.js:396)
    at tokenHotbar_TokenHotbar.removeTokenMacros (TokenHotbar.js:465)
    at TokenHotbar.js:853
    at Function._call (foundry.js:2496)
    at Function.call (foundry.js:2481)
    at foundry.js:30109
    at Array.reduce (<anonymous>)
    at Scene.deleteEmbeddedEntity (foundry.js:30104)
    at multilevel.js:693
_call @ foundry.js:2499
8multilevel.js:215 Uncaught (in promise) TypeError: Cannot read property 'flags' of undefined
    at MultilevelTokens._isReplicatedToken (multilevel.js:215)
    at Function.updateAttachedCreatedToken (token-attacher.js:1448)
    at token-attacher.js:192
    at Function._call (foundry.js:2496)
    at Function.callAll (foundry.js:2456)
    at Function._handleCreateEmbeddedEntity (foundry.js:29908)
    at Function._handleCreateEmbeddedEntity (foundry.js:34286)
    at Scene.createEmbeddedEntity (foundry.js:29879)
mountManager.js:147 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at Function.handleTokenDelete (mountManager.js:147)
    at mountup.js:60
    at Function._call (foundry.js:2496)
    at Function.call (foundry.js:2481)
    at foundry.js:30109
    at Array.reduce (<anonymous>)
    at Scene.deleteEmbeddedEntity (foundry.js:30104)
    at multilevel.js:693
foundry.js:29917 Foundry VTT | Created ActiveEffect 4K6xDNj3wb9EfuEh in parent Actor NzEwNDQxMmQ5ZjI2
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gwydgen
foundry.js:29917 Foundry VTT | Created ActiveEffect ZOOZtutHhhof4ziT in parent Actor NzEwNDQxMmQ5ZjI2
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gwydgen
foundry.js:29917 Foundry VTT | Created ActiveEffect BUWDfYk5KUtJ0eIW in parent Actor NzEwNDQxMmQ5ZjI2
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gwydgen
foundry.js:30175 Foundry VTT | Deleted Token Z7KjdEe9s71tyx7z from parent Scene smnoSnaCweGURXMe
foundry.js:29917 Foundry VTT | Created ActiveEffect cPjxiY0AiPGwHOEB in parent Actor NzEwNDQxMmQ5ZjI2
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gwydgen
foundry.js:29917 Foundry VTT | Created ActiveEffect OqJlKmdVSCG9aDId in parent Actor NzEwNDQxMmQ5ZjI2
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gwydgen
foundry.js:29917 Foundry VTT | Created ActiveEffect Xmt8Wnga9TIlpaaR in parent Actor NzEwNDQxMmQ5ZjI2
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gwydgen
foundry.js:29917 Foundry VTT | Created ActiveEffect 9n6jEgrV5ZKJeniT in parent Actor NzEwNDQxMmQ5ZjI2
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gwydgen
foundry.js:29917 Foundry VTT | Created ActiveEffect nKORmorbbtJxU4rw in parent Actor NzEwNDQxMmQ5ZjI2
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gwydgen
foundry.js:29917 Foundry VTT | Created ActiveEffect Qvffi9u2IJzcDttL in parent Actor NzEwNDQxMmQ5ZjI2
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gwydgen
foundry.js:29917 Foundry VTT | Created Token tcj9Fv3txKlFFFbU in parent Scene smnoSnaCweGURXMe
multilevel.js:215 Uncaught (in promise) TypeError: Cannot read property 'flags' of undefined
    at MultilevelTokens._isReplicatedToken (multilevel.js:215)
    at Function.updateAttachedCreatedToken (token-attacher.js:1448)
    at token-attacher.js:192
    at Function._call (foundry.js:2496)
    at Function.callAll (foundry.js:2456)
    at Function._handleCreateEmbeddedEntity (foundry.js:29908)
    at Function._handleCreateEmbeddedEntity (foundry.js:34286)
    at Scene.createEmbeddedEntity (foundry.js:29879)
foundry.js:29917 Foundry VTT | Created ActiveEffect l1MIrFWHz1inkzyN in parent Actor NzEwNDQxMmQ5ZjI2
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gwydgen
foundry.js:29917 Foundry VTT | Created ActiveEffect wFzn0qffCOBitage in parent Actor NzEwNDQxMmQ5ZjI2
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gwydgen
foundry.js:29917 Foundry VTT | Created ActiveEffect McNv0h61xiV3aGTr in parent Actor NzEwNDQxMmQ5ZjI2
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to Gwydgen
foundry.js:29917 Foundry VTT | Created ActiveEffect ndMajlIJuG2qT6bz in parent Actor M2JhZjcxNzM5Y2U0
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to  Irid Ionian the Fifth 
foundry.js:29917 Foundry VTT | Created ActiveEffect BsWSKzlKRuvEe8GL in parent Actor M2JhZjcxNzM5Y2U0
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to  Irid Ionian the Fifth 
foundry.js:29917 Foundry VTT | Created ActiveEffect EkxDtdnpHqWBYiMX in parent Actor M2JhZjcxNzM5Y2U0
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to  Irid Ionian the Fifth 
foundry.js:29917 Foundry VTT | Created ActiveEffect CfpS1An9qw38fHp8 in parent Actor M2JhZjcxNzM5Y2U0
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to  Irid Ionian the Fifth 
foundry.js:29917 Foundry VTT | Created ActiveEffect 2P2vE5cJoOvG7Z3Y in parent Actor M2JhZjcxNzM5Y2U0
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to  Irid Ionian the Fifth 
foundry.js:29917 Foundry VTT | Created ActiveEffect PThjOEq5nfshQek4 in parent Actor M2JhZjcxNzM5Y2U0
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to  Irid Ionian the Fifth 
log.js:33 WebPing: doPings: sucess - 35
log.js:33 WebPing: emitting data
log.js:33 WebPing: doPings: set pingData.data to - 19,26,16,24,26,19,22,31,19,17,16,31,17,16,22,14,15,20,28,16,19,30,30,20,155,25,16,33,29,35
log.js:33 WebPing: doPings: set pingData.median to - 21
log.js:33 chartResponse: updating chart
log.js:33 WebPing: updated chart
foundry.js:29917 Foundry VTT | Created ActiveEffect lcDkO8vh0h1cdHxs in parent Actor M2JhZjcxNzM5Y2U0
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to  Irid Ionian the Fifth 
foundry.js:29917 Foundry VTT | Created ActiveEffect GTf9rqfKI5yXJp4S in parent Actor M2JhZjcxNzM5Y2U0
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to  Irid Ionian the Fifth 
foundry.js:29917 Foundry VTT | Created ActiveEffect I23PfCgXyQZAEf4T in parent Actor M2JhZjcxNzM5Y2U0
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to  Irid Ionian the Fifth 
foundry.js:29917 Foundry VTT | Created ActiveEffect OJzb6AfPgVdS0tM1 in parent Actor M2JhZjcxNzM5Y2U0
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to  Irid Ionian the Fifth 
foundry.js:29917 Foundry VTT | Created ActiveEffect PsSJlS5JV8GFfNhG in parent Actor M2JhZjcxNzM5Y2U0
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to  Irid Ionian the Fifth 
foundry.js:29917 Foundry VTT | Created ActiveEffect a9xLe3qEIacDBK6J in parent Actor M2JhZjcxNzM5Y2U0
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to  Irid Ionian the Fifth 
foundry.js:29917 Foundry VTT | Created ActiveEffect w7YLpirzjZ567ZCo in parent Actor M2JhZjcxNzM5Y2U0
aura.js:493 ActiveAuras | Applied 'Aura of Protection' to  Irid Ionian the Fifth 
foundry.js:2498 Foundry VTT | Error thrown in hooked function bound controlToken
_call @ foundry.js:2498
foundry.js:2499 Error: The values of the provided object must be unique in order to invert it.
    at invertObject (foundry.js:1129)
    at Function.get defaultLanguage [as defaultLanguage] (polyglot.js:49)
    at PolyGlot.updateUserLanguages (polyglot.js:175)
    at PolyGlot.controlToken (polyglot.js:82)
    at Function._call (foundry.js:2496)
    at Function.callAll (foundry.js:2456)
    at Token.control (foundry.js:11629)
    at Token._onClickLeft (foundry.js:11858)
    at Token._onClickLeft (foundry.js:45385)
    at O._call_wrapped (wrapper.js:298)
_call @ foundry.js:2499
foundry.js:39692 You are calling the SightLayer#update method which has been renamed to SightLayer#refresh to be consistent with other PIXI objects.
update @ foundry.js:39692
dnd5e-actions.js:419 Uncaught (in promise) TypeError: Cannot read property 'charAt' of undefined
    at dnd5e-actions.js:419
    at Array.map (<anonymous>)
    at ActionHandler5e._getSkillsList (dnd5e-actions.js:416)
    at ActionHandler5e.doBuildActionList (dnd5e-actions.js:45)
    at ActionHandler5e.buildActionList (actionHandler.js:32)
    at TokenActionHUD.updateHud (tokenactionhud.js:386)

**Comment by JustinKovacich** [comment]
![image](https://user-images.githubusercontent.com/32140377/107972841-6cfec680-6f82-11eb-8666-b2a17463d30d.png)
![image](https://user-images.githubusercontent.com/32140377/107972874-79831f00-6f82-11eb-9fda-84b82df44783.png)
(Frightened immunity is one of the benefits conferred by the aura)

**Comment by kandashi** [comment]
Can you export the scene, actors and active modules and send them over

**Comment by Juanfrank** [comment]
To contribute on this issue, using the "Actor Folder drop on canvas" action seems to apply several instances of the same aura to the tokens contained in the radius of the emitting token. These tokens have one or several instances of the Aura which cannot be toggled or deleted, having to manually delete them from an exported json then re-importing back).

Steps to reproduce:
1. Have an actor folder with a token with an active aura.
2. Drop on canvas.
3. Watch as the tokens with are within the radius get added the aura (in this case Aura of Protection). The amount seems to be random.
4. Watch as some of the active auras cannot be toggled off, deleted, and do not delete even if they get out of radius or the active effect source is toggled or deleted.
