### ISSUE TITLE
Bug? Params in macro.execute

### ISSUE THREAD

**Issue by MSAbaddon** [kandashi/Active-Auras#62]
Hi,
I don't know if this is a DAE or an Active Auras bug. The only module I updated was DAE, but the problem only occurs for Active Auras as far as I can tell.

It no longer seems to be possible to pass params to the executed macro.

If I use CreateBonfireEffect as Effect Value everything works fine.
If I use CreateBonfireEffect @token I get the following error message.

![image](https://user-images.githubusercontent.com/66370966/107861474-3328a580-6e46-11eb-8725-218ce2b166a4.png)

![image](https://user-images.githubusercontent.com/66370966/107861483-518ea100-6e46-11eb-8742-2cc3040570c0.png)

**Comment by kandashi** [comment]
I can replicate this, a fix should go out in the next patch

**Comment by MSAbaddon** [comment]
Nice :-)

**Comment by MSAbaddon** [comment]
Got a similar issue with dae core functionality - created a separate issue there.

https://gitlab.com/tposney/dae/-/issues/127
