### ISSUE TITLE
Timed Auras

### ISSUE THREAD

**Issue by LuxuriaU** [kandashi/Active-Auras#68]
Not sure if this is clearly not supported, or not supported yet, but I was wondering if timed auras are known to not work or are not meant to. I took the example aura as a good control, confirmed it was working, then made it a self-cast with a timer of one (1) minute. When used, it applied the aura, however, on allies it appeared as undefined, and furthermore, removing it from the caster (originator) of the aura, it continued to be cast unto allies around it, even when time was advanced (recipients also got a separate timer for the aura when applied to them, though the aura correctly was removed when outside of 10 feet).

Are timed auras not possible due to how this works, or is this an issue on my end? Additionally, are auras known to only update after new tokens are placed in terms of the charisma mod when using the Aura of Protection example. Changes do not reflect in real-time, but I can see why that is the case, giving the nature of the module if so. Just thought to tack that one instead of making a separate post altogether.

Thank you in advance, this module is still really impressive.

**Comment by kandashi** [comment]
It should work as intended. What aura did you test with?

As for the cha mod updates, you will have to retrigger the collection of auras (turn if on/off).

**Comment by LuxuriaU** [comment]
I turned the Aura of Protection into a "times" aura by making it an action > target self >duration 1 minute.

My goal was to test to see if spells that give the caster an aura could work, but in this case the aura, when transferred to a new token; 

- It gave them the effect with one minute remaining (no matter how long the spell had left. 
- Once they leave the aura, I cannot figure out how to make the effects stick (this is likely my fault though).
- Lastly, once the effect reached the end of its duration (as in, the spell should no longer be active) the caster still had said aura.

Not sure, again, if this is just not the intended use of the module, the real-time auras work great, for ones that confer lasting effects are not something I can figure out, as are timed auras.

**Comment by kandashi** [comment]
Im not quite sure what you mean, any effects applied through AA will expire when the token that owns the aura looses that aura (of moves out of range), it will not persist after that time.

As for the other issues those are not covered by AA, you probably need https://gitlab.com/tposney/about-time or https://gitlab.com/tposney/times-up

**Comment by LuxuriaU** [comment]
Have those, yeah think something got lost in translation, which is fine. All good, enjoying the module though, cheers.
