### ISSUE TITLE
Aura do not work for friendly token

### ISSUE THREAD

**Issue by Darshyne** [kandashi/Active-Auras#69]
Hello,
since last update Aura do not work for friendly token.

**Comment by dennywright** [comment]
I'm having a similar issue. Here's a log capture. I'm using the premade Aura of Protection (DAE).
I moved a token without the Aura into range of a token with the Aura. 

aura.js:215 movement, main aura
aura.js:397 movement update
aura.js:420 Map(1) {"Aura of Protection-eMJ9q3f9I2Ht09xN" => {…}}
patching.js:11 Uncaught (in promise) TypeError: Cannot read property 'save' of undefined
    at Actor5e.rollAbilitySave (patching.js:11)
    at O.call_wrapper (wrapper.js:398)
    at Actor5e.doAbilityRoll (patching.js:165)
    at Actor5e.rollAbilitySave (patching.js:182)
    at O.call_wrapper (wrapper.js:421)
    at Actor5e.🎁@handler0(CONFIG.Actor.entityClass.prototype.rollAbilitySave) (wrapper.js:133)
    at CreateActiveEffect (aura.js:571)
    at MainAura (aura.js:423)
    at aura.js:216
    at Function._call (foundry.js:2496)
    at Function.callAll (foundry.js:2456)
    at Function._handleUpdateEmbeddedEntity (foundry.js:30047)
    at Function._handleUpdateEmbeddedEntity (foundry.js:34301)
    at Scene.updateEmbeddedEntity (foundry.js:30015)
rollAbilitySave @ patching.js:11
call_wrapper @ wrapper.js:398
doAbilityRoll @ patching.js:165
rollAbilitySave @ patching.js:182
call_wrapper @ wrapper.js:421
🎁@handler0(CONFIG.Actor.entityClass.prototype.rollAbilitySave) @ wrapper.js:133
CreateActiveEffect @ aura.js:571
MainAura @ aura.js:423
(anonymous) @ aura.js:216
_call @ foundry.js:2496
callAll @ foundry.js:2456
_handleUpdateEmbeddedEntity @ foundry.js:30047
_handleUpdateEmbeddedEntity @ foundry.js:34301
updateEmbeddedEntity @ foundry.js:30015
async function (async)
(anonymous) @ aura.js:216
_call @ foundry.js:2496
callAll @ foundry.js:2456
_handleUpdateEmbeddedEntity @ foundry.js:30047
_handleUpdateEmbeddedEntity @ foundry.js:34301
updateEmbeddedEntity @ foundry.js:30015
async function (async)
updateEmbeddedEntity @ foundry.js:30005
updateMany @ foundry.js:12448
moveMany @ foundry.js:12390
_handleMovement @ foundry.js:3059
(anonymous) @ foundry.js:3028
setTimeout (async)
_onMovement @ foundry.js:3028
_handleKeys @ foundry.js:2806
_onKeyDown @ foundry.js:2761

**Comment by kandashi** [comment]
So any old versions of the auras need a quick update to fix for the latest release, if you go into the aura details and type anything into the save/type fields, then delete the text and save the aura that should fix the issues

**Comment by kandashi** [comment]
The premade ones should be properly fixed in the next update too.

**Comment by dennywright** [comment]
Thanks

**Comment by dennywright** [comment]
Sorry, Kandashi. I'm seeing a slightly different exception after today's update, v1.44. Cannot read property 'toLowerCase' of undefined. I tried importing the AoP DAE premade, then updating both type/save, then deleting, then adding to the paladin. Getting this exception every time a token moves (debugging on). Hope this helps. 
BTW, Thanks for this module.
Denny (@Flint Falcon in discord)

aura.js:207 movement, main aura
aura.js:389 movement update
aura.js:412 Map(0) {}
aura.js:478 Uncaught (in promise) TypeError: Cannot read property 'toLowerCase' of undefined
    at UpdateToken (aura.js:478)
    at UpdateAllTokens (aura.js:434)
    at MainAura (aura.js:406)
    at aura.js:208
    at Function._call (foundry.js:2496)
    at Function.callAll (foundry.js:2456)
    at Function._handleUpdateEmbeddedEntity (foundry.js:30047)
    at Function._handleUpdateEmbeddedEntity (foundry.js:34301)
    at Scene.updateEmbeddedEntity (foundry.js:30015)
UpdateToken @ aura.js:478
UpdateAllTokens @ aura.js:434
MainAura @ aura.js:406
(anonymous) @ aura.js:208
_call @ foundry.js:2496
callAll @ foundry.js:2456
_handleUpdateEmbeddedEntity @ foundry.js:30047
_handleUpdateEmbeddedEntity @ foundry.js:34301
updateEmbeddedEntity @ foundry.js:30015
async function (async)
updateEmbeddedEntity @ foundry.js:30005
updateMany @ foundry.js:12448
moveMany @ foundry.js:12390
_handleMovement @ foundry.js:3059
(anonymous) @ foundry.js:3028
setTimeout (async)
_onMovement @ foundry.js:3028
_handleKeys @ foundry.js:2806
_onKeyDown @ foundry.js:2761
foundry.js:39342 Saved Fog of War exploration progress in Scene xucTfvJPxXbAmeZq
