### ISSUE TITLE
"Cannot read property 'toLowerCase' of undefined"

### ISSUE THREAD

**Issue by MS-PBS** [kandashi/Active-Auras#75]
I'm getting this error with a macro execute effect, and the macro does not execute:

![Captura](https://user-images.githubusercontent.com/68601994/108890476-8a2c3880-7605-11eb-812d-65c0d478044f.JPG)

Rolling back to version 1.35 fixes this issue. The macro is:

```js
function check_sight_obscured(reciever){
    return Math.max(0,
        reciever.actor.data.data.attributes.senses.blindsight, 
        reciever.actor.data.data.attributes.senses.tremorsense
        );
}

let reciever = canvas.tokens.get(args[1]);
console.log(args, typeof(args[1]));
console.log(reciever, reciever.actor);
//console.log('check');
switch (args[0]) {
    
    case 'on': {
        game.cub.addCondition('Obscured', reciever, {warn:false});
        reciever.setFlag('perfect-vision','sightLimit',check_sight_obscured(reciever));
        //console.log('enter');
    }
        break;
        
    case 'off': {
        game.cub.removeCondition('Obscured', reciever, {warn:false});
        reciever.unsetFlag('perfect-vision','sightLimit', reciever);
        //console.log('leave');
    }
        break;
}
```

**Comment by kandashi** [comment]
Go into the effect and add any text to the `type` and `save` field, then delete the text and save the effect, that should fix

**Comment by MS-PBS** [comment]
Yes, I didn't manage to make it work (maybe I did something wrong), but it gave me the idea to remake the effect from scratch, and that seems to have fixed it. Thank you!
