### ISSUE TITLE
Aura of Protection demo needs minimum of +1 CHA applied

### ISSUE THREAD

**Issue by MalakanC** [kandashi/Active-Auras#78]
Just testing the module and I added the feature to an actor with 9 Charisma, this means +@abilities.cha.mod applies -1 CHA to anyone within the aura when should be +1 minimum

I tried modifying the effect value to `+{@abilities.cha.mod,1}kh` which seems to work but doesn't look pretty in the chat window.

With Charisma of 9:
![image](https://user-images.githubusercontent.com/39969354/109016329-fd898500-76ad-11eb-9f78-f6542d7cb94b.png)

With a Charisma of 14
![image](https://user-images.githubusercontent.com/39969354/109016438-17c36300-76ae-11eb-851b-dfb454e14f6c.png)

**Comment by MalakanC** [comment]
That test was done only with the actor who possessed the aura ability. Doesn't work with other actors who have been given the aura effect.

**Comment by kandashi** [comment]
im afraid this is a limitation of the module, simply replace the +@ability value with 1
