### ISSUE TITLE
Aura not effecting correct tiles when using a large size token to emit aura

### ISSUE THREAD

**Issue by MalakanC** [kandashi/Active-Auras#80]
Use of a large token doesn't apply the aura evenly around the token.

In the image below, the same aura is applied to each token, 10 ft radius. For the large token I have marked in purple the squares that give another token in that square the aura's effect.

![image](https://user-images.githubusercontent.com/39969354/109104682-54ca3c80-7724-11eb-8477-a602fb6b5e31.png)

Only tested on large and medium as of writing this.

**Comment by kandashi** [comment]
are you on a build pre-0.1.43 as this should be fixed

**Comment by MalakanC** [comment]
Current version is 0.1.47, i believe i started pre-0.1.43.

On a fresh world it works as intended. On my main world it does not.

Deactivating and re-activating seems to have triggered one of the fixes, the host token glows now which it wasn't before. The effected squares remain the same as the image above however.

Creating a new scene and bringing the tokens in results in the host token not glowing as intended and the same tile issue as above.

**Comment by kandashi** [comment]
The "glowing issue" is just how TMFX works. Try deleting and re-making the aura item

**Comment by MalakanC** [comment]
That does fix the glow issue on the host token. Doesn't change the affected tiles.

**Comment by kandashi** [comment]
what measurement system are you using?

**Comment by MalakanC** [comment]
5/10/5 DMG

**Comment by MalakanC** [comment]
Checked just now, with the 5/5/5 PHB measure setting it works as intended. So something wrong with DMG measurements

**Comment by MSAbaddon** [comment]
Have the same issue, 5/10/5 measurement, latest release installed.

Did some more tests.

A 15 on a huge creature looks like this (the measured template is green, the circles mark the affected squares)
![image](https://user-images.githubusercontent.com/66370966/109206128-c5666d00-77a7-11eb-8511-c022ef126c69.png)

**Comment by kandashi** [comment]
Right, I'll have a look into this then now we've narrowed it down a bit

**Comment by MalakanC** [comment]
It's symmetric from the top left to the bottom right in these two cases. Is top left towards 0,0?

**Comment by kandashi** [comment]
I cannot seem to replicate this on any of the settings. Could you try reinstalling AA and if that dosnt work send me a PM with an invite to your sever and I'll come and check locally

**Comment by MSAbaddon** [comment]
Finally found the time to do some more testing. With the current version of active auras the range problem seems to be solved :-)
