### ISSUE TITLE
Errors when adding active aura

### ISSUE THREAD

**Issue by MSAbaddon** [kandashi/Active-Auras#82]
Currently, the application of effects seems to be somewhat buggy.

E.g.: When I drag'n'drop the premade aura "Aura of Protection" to a token's character sheet, I see it as a passive effect on the token, but it has no effect at all - neither on the token itself nor on other tokens moving into the area of effect. Even more, if a token moves into the aoe, I get the following error message:

![image](https://user-images.githubusercontent.com/66370966/109208230-5b02fc00-77aa-11eb-91e8-6505a82f46e9.png)

I actually have to do some editing within the active effect and save the changes. After this the aura works correct.

**Comment by kandashi** [comment]
Yes, Tposney has contacted me about this. Will be fixed soon
