### ISSUE TITLE
Errors being thrown on each token movement

### ISSUE THREAD

**Issue by Deuterazamus** [kandashi/Active-Auras#83]
Errors are being spammed on console:
![image](https://user-images.githubusercontent.com/68236513/109428929-892a4b00-79f9-11eb-9577-38acd4ec5ddc.png)

Reproduction is easy and consistent:
- create new 5e test world
- add a player account
- activate modules Active-Auras 0.1.48, DAE 0.2.52, and libwrapper 1.3.5.0 (all to the latest version)
- create new a scene
- create an actor and place it on the created scene. Give it ownership to the player account
- leave the GM connected and open another window/client logging in with the player account
- move the token either from the GM or player window
- check the Player console

Of course the stacktrace differs slightly when is initiated gmside or playerside, but the faulty line is the same.
Attaching preconfigured test world.

[testaa.zip](https://github.com/kandashi/Active-Auras/files/6057599/testaa.zip)

**Comment by Arcainne** [comment]
I resolved this locally by adding optional chaining to a few places in `aura.js` to make sure nothing is being called on an `undefined` object,
**Before**
```
aura.js:311:  if (!MapObject.effects) return;
aura.js:383:  MapObject.effects.forEach(i => EffectsArray.push(i.data.origin))
aura.js:502:  let checkEffects = MapObject.effects;
```
**After**
```
aura.js:311:  if (!MapObject?.effects) return false;
aura.js:383:  MapObject?.effects.forEach(i => EffectsArray.push(i.data.origin))
aura.js:502:  let checkEffects = MapObject?.effects ?? [];
```

**Comment by Deuterazamus** [comment]
@Arcainne while I do agree that your modifies suppress the problem at hand, I wonder how much of the code of aura.js shoud actually be executed playerside. From what I can understand of the actual code CollateAuras/MainAura are the core methods that compute everything both are bound to be executed only on the gm machine (line 321 and 405). 
The code hooked on updateToken, for example, relies on what has been computed gmside in CollateAuras but will execute playerside against an empty AuraMap, thus the error.
Is it possible that all hooks should be gm only? 
Are the current gm-only guards a bit too deep in the execution and could be moved up at hooks level? 
I'm not nearly familiar enough with Foundry+ActiveAuras inner working so please take my suggestion with a grain of salt

**Comment by kandashi** [comment]
Yeah this is a good note, will be fixed soon
