### ISSUE TITLE
Updating Aura Values Between Two Similar Auras

### ISSUE THREAD

**Issue by Tyaeth** [kandashi/Active-Auras#84]
Hi there!

My group just swapped over to Foundry and we've been using Active Auras and DAE to do some of our class features, namely the paladins Aura of Protection. The Aura has been working as expected when we apply it to one of our paladins, but our game has two paladins and we've been noticing some issues in how their auras interact with each other.

Assuming that both paladins are using the premade Aura of Protection (DAE) included in the compendium, and
PaladinA = +2CHA
PaladinB = +3CHA

Issue1: Actors are only being affected by the first aura that they come into contact with, rather than the strongest. PaladinA is never affected by PaladinB's aura, and any actors that are affected by PaladinA's aura maintain the weaker aura if PaladinB steps into range. 

Issue 2: Aura values don't update when passing from one aura to another with the same name. If Druid is sitting in PaladinB's aura and enjoying a +3 bonus, but then moves into PaladinB's aura, he maintains the +3 bonus despite not being within range of the original aura.

**Comment by kandashi** [comment]
Looking into this
