### ISSUE TITLE
Aura only working if other PC moves in range, not PC with aura moving.

### ISSUE THREAD

**Issue by Draino23** [kandashi/Active-Auras#85]
I am trying to setup an aura on a shield that adds fire resistance to allies within 5ft. 

I have the aura setup like this:
![image](https://user-images.githubusercontent.com/38112487/109447341-0f01c280-7a09-11eb-868e-23667cc7ff50.png)

When the actor with the shield moves toward allies I the following in the debug log:

`Uncaught (in promise) TypeError: tokenEffects.data.flags.ActiveAuras is undefined
    RemoveActiveEffects aura.js:694
    MainAura aura.js:432
    <anonymous> aura.js:221
    _call foundry.js:2496
    callAll foundry.js:2456
    _handleUpdateEmbeddedEntity foundry.js:30047
    _handleUpdateEmbeddedEntity foundry.js:34301
    updateEmbeddedEntity foundry.js:30015
    update foundry.js:11475
    animateToken foundry_imports.js:64
    moveTokens foundry_imports.js:35
    moveTokens foundry_imports.js:32
    onTokenDragLeftDrop main.js:171
    _onDragLeftDrop main.js:56
    callback foundry.js:36392
    _handleDragDrop foundry.js:36767
    _handleMouseUp foundry.js:36737
    emit index.js:181
    dispatchEvent InteractionManager.ts:1106
    processPointerUp InteractionManager.ts:1459
    recursiveFindHit TreeSearch.ts:173
    recursiveFindHit TreeSearch.ts:113
    recursiveFindHit TreeSearch.ts:113
    recursiveFindHit TreeSearch.ts:113
    findHit TreeSearch.ts:200
    processInteractive InteractionManager.ts:1177
    onPointerComplete InteractionManager.ts:1341
    onPointerUp InteractionManager.ts:1409
aura.js:694:17
`

If I instead move the allied actor toward the character with the shield the aura works properly.

**Comment by kandashi** [comment]
Can you try disabling then re-enabling the aura on the source token

**Comment by Draino23** [comment]
This seems to work kinda, Though I am now having a opposite issue, though only when two aura are in use on separate actors.

For example, I am using CUB conditional lab. I have created two custom conditions each with an effect with an aura. One applied fire resistance withing 5 ft, and the other applied +1 AC within 10 ft. 
![image](https://user-images.githubusercontent.com/38112487/110194514-2d4b3200-7dfe-11eb-9f66-4fac0a1fa4df.png)
On each actor this work fine. 

If I move an actor into range of the other actor with the aura, then the aura isnt being applied.
![image](https://user-images.githubusercontent.com/38112487/110194562-6be0ec80-7dfe-11eb-90d9-e4dd1ea56de5.png)
In the above image the actor with the fire shield should also have the +1 AC condition.

If I move the actor with the condition I need applied it updates correctly:
![image](https://user-images.githubusercontent.com/38112487/110194634-cd08c000-7dfe-11eb-8a19-0d71167bccd8.png)

But now if I move the actor with the fire shield away the +1AC condition is not removed as it should be.
![image](https://user-images.githubusercontent.com/38112487/110194657-f0cc0600-7dfe-11eb-94b6-269c3301aa56.png)

This issue is present for both the fire shield condition and the +1 AC condition.

**Comment by kandashi** [comment]
This was a bug with 0.1.52 if I remember, try updating to the latest version

**Comment by Draino23** [comment]
I am still getting it in 1.54
![image](https://user-images.githubusercontent.com/38112487/110222577-dc3c4c00-7e98-11eb-9b61-bd51d328f651.png)

Only thing I am seeing in the console with debug is:
![image](https://user-images.githubusercontent.com/38112487/110222628-33422100-7e99-11eb-8f09-13eda01adc33.png)

**Comment by kandashi** [comment]
That is saying it doesn't recognise the auras. Check over the aura details and try re-adding then to the actors

**Comment by Draino23** [comment]
Okay I recreated the auras as features instead of effects with in Condition Lab:
![image](https://user-images.githubusercontent.com/38112487/110247419-d34b8900-7f31-11eb-8693-0caede5fca85.png)
and configured their auras:
![image](https://user-images.githubusercontent.com/38112487/110247434-e2323b80-7f31-11eb-83a7-66a3cff762aa.png)

After that it still is not working
![recording](https://user-images.githubusercontent.com/38112487/110247521-4654ff80-7f32-11eb-9334-debbab4b86a1.gif)

**Comment by dmaneyapanda** [comment]
I am having the same problem, but I think I have identified the issue.  
* When the targets are moving, the aura applies and removes as expected
* When the source is moving, the auras apply as expected, but once applied they do not remove until all potential aura targets are out of range.  So some targets keep the aura longer than they should.

**Comment by kandashi** [comment]
If possible could you invite me to your game (pm on discord is fine) so I can test locally

**Comment by Draino23** [comment]
Messaged
