### ISSUE TITLE
Two Paladin Problem

### ISSUE THREAD

**Issue by dennywright** [kandashi/Active-Auras#91]
Currently on 0.1.52

I have two Paladins with Aura of Protection; Paladin A with +5 bonus and B with +3 bonus. When they are within each other's aura, Paladin A has +5, but Paladin B has +3+5.

Tip: I'm using Token Tooltip Alt with a display for bonuses.abilities.save to see the result of the Auras.

Paladin A keeps his +5 Active Effect (still referencing +@abilities.cha.mod) and B's +3 Active Effect is ignored, where as Paladin B keeps her +3 Active Effect (still referencing +@abilities.cha.mod), but also gets A's +5 Active Effect. 

From what I can tell, it seems problematic to remove B's original Active Effect. Some solutions I've thought of:
1) Do the math to apply a +2 Active Effect to B. 
2) Disable B's Active Effect and enable it when she's out of A's aura (not sure if something else would enable it automagically).
3) Keep track of B's Active Effect elsewhere and reapply when she's out of A's aura.

**Comment by kandashi** [comment]
Hum, i can replciate this. I'll look into it

**Comment by kandashi** [comment]
So this is a difficult one, Either the second paladin gets both saves, or doesnt get the bonus from the other aura at all

**Comment by dennywright** [comment]
I like the idea of solution 2 the best. I can manually toggle B’s original Effect to inactive and back (either on the Effects tab or using Token HUD). I’m not sure how to do it programmatically. Would that be updateEmbeddedEntity()?

**Comment by kandashi** [comment]
yup, `updateEmbeddedEntity(_id : id, {changes})` i believe

**Comment by kandashi** [comment]
A fix to resolve this will go out soon. Any token providing an aura will no longer be affected by an aura of the same name

**Comment by dennywright** [comment]
Unfortunately, this fix didn't have the expected result. The most potent effect should take effect. Paladin B should get Paladin A's +5  aura.

**Comment by dennywright** [comment]
My bad. That last part was something I did.
