### ISSUE TITLE
Variable Aura Values Not Changing On Aura Recipients

### ISSUE THREAD

**Issue by Tyaeth** [kandashi/Active-Auras#93]
If an actor has an aura that provides a bonus that relies on a stat (lets say Aura of Protection granting a `+@abilities.cha.mod` bonus to `data.bonuses.abilities.save`), the value of the aura for other actors that doesn't update for recipients of the aura.

Example: 
Paladin has a +2 CHA modifier, and Aura of Protection grants themselves and others a +2 bonus to saves. If the paladin levels up and ups their Charisma to a +3 modifier, they appropriately get a +3 bonus to their saves. However, anyone else who walks into range of the aura (even if the aura is reapplied by walking out of range and back in) will still only get a +2 bonus, even if the aura is refreshed on them by them walking out of and back into range.

**Comment by kandashi** [comment]
This is an unfortunate limitation. The quick fix is to turn the aura effect on/off and that will reset it,
